import "mir_layout.gst" as layout;
import "mir_function_abi_authority.gst" as abi;
import "mir_fat_pointer_abi.gst" as fat;
import "mir_fat_pointer_abi_mir_to_c.gst" as mir_to_c;
import "mir_native_backend_fat_pointer_abi_request.gst" as fat_request;
func fail(message: str) { os.LogStr(message); os.Exit(1); }
func method_abi(target: str, triple: str, ctx: &Arena) abi.MirFunctionAbiIdentity[ctx] {
    mut value: abi.MirFunctionAbiIdentity[ctx]; value.abi_id = std.Clone(ctx, "abi:trait_value_method"); value.function_id = std.Clone(ctx, "mir.function.trait_value_method"); value.signature_id = std.Clone(ctx, "sig:borrowed_trait_object_to_i32"); value.calling_convention = std.Clone(ctx, "gust"); value.target_id = std.Clone(ctx, target); value.target_triple = std.Clone(ctx, triple); value.parameter_placement_ids = abi.mir_abi_empty_str_vector(ctx); value.result_placement_ids = abi.mir_abi_empty_str_vector(ctx); return value;
}
func selected_call(data_layout: str, metadata_layout: str, target: str, triple: str, ctx: &Arena) fat.MirFatPointerTraitCall[ctx] {
    mut value: fat.MirFatPointerTraitCall[ctx]; value.call_id = std.Clone(ctx, "fat_pointer_call:trait_value"); value.fat_pointer_id = std.Clone(ctx, "fat_pointer:borrowed_display_object"); value.trait_object_id = std.Clone(ctx, "trait_object:DisplayLike"); value.form = std.Clone(ctx, "borrowed_trait_object_method_call"); value.representation = std.Clone(ctx, "two_word_data_and_vtable"); value.data_component_id = std.Clone(ctx, "component:data:object_7"); value.data_type_id = std.Clone(ctx, "type:*borrowed_object_data"); value.data_layout_id = std.Clone(ctx, data_layout); value.data_placement = std.Clone(ctx, "fat_pointer.word0.data"); value.metadata_component_id = std.Clone(ctx, "component:vtable:DisplayLike_for_object_7"); value.metadata_type_id = std.Clone(ctx, "type:*DisplayLike_vtable"); value.metadata_layout_id = std.Clone(ctx, metadata_layout); value.metadata_placement = std.Clone(ctx, "fat_pointer.word1.vtable"); value.metadata_present = 1; value.pair_id = std.Clone(ctx, "pair:object_7:DisplayLike"); value.actual_pair_id = std.Clone(ctx, "pair:object_7:DisplayLike"); value.vtable_id = std.Clone(ctx, "vtable:DisplayLike_for_object_7"); value.actual_vtable_id = std.Clone(ctx, "vtable:DisplayLike_for_object_7"); value.method_signature_id = std.Clone(ctx, "sig:borrowed_trait_object_to_i32"); value.actual_method_signature_id = std.Clone(ctx, "sig:borrowed_trait_object_to_i32"); value.slot_id = std.Clone(ctx, "vtable_slot:DisplayLike:value:0"); value.actual_slot_id = std.Clone(ctx, "vtable_slot:DisplayLike:value:0"); value.slot_ordinal = 0; value.call_abi_id = std.Clone(ctx, "abi:trait_value_method"); value.actual_call_abi_id = std.Clone(ctx, "abi:trait_value_method"); value.operations = std.Clone(ctx, "construct_fat_pointer,extract_vtable_method,typed_indirect_call"); value.required_alignment = 8; value.actual_alignment = 8; value.resource_disposition = std.Clone(ctx, "borrowed_no_transfer_state_live"); value.expected_result = 42; value.actual_result = 42; value.target_id = std.Clone(ctx, target); value.actual_target_id = std.Clone(ctx, target); value.target_triple = std.Clone(ctx, triple); value.actual_target_triple = std.Clone(ctx, triple); value.source_location = std.Clone(ctx, "compiler/phase16_fat_pointer_source.gst:12:5"); return value;
}
func main() {
    mut ctx := os.Arena.New(); defer ctx.Free(); os.SetThreadScratch(ctx); mut target_id := "target:x86_64-unknown-linux-gnu"; mut triple := "x86_64-unknown-linux-gnu";
    mut target := layout.mir_layout_make_target_v2(target_id, triple, "little", 8, 8, 4, 8, 16, &ctx); mut layouts := layout.mir_layout_make_table(target, &ctx);
    mut data := layout.mir_layout_make_scalar_type_layout("type:*borrowed_object_data", target_id, "pointer", 8, 8, 64, "unsigned", "any_bit_pattern", &ctx); mut metadata := layout.mir_layout_make_scalar_type_layout("type:*DisplayLike_vtable", target_id, "pointer", 8, 8, 64, "unsigned", "any_bit_pattern", &ctx); layouts = layout.mir_layout_table_with_layout(layouts, data, &ctx); layouts = layout.mir_layout_table_with_layout(layouts, metadata, &ctx);
    mut authority := abi.mir_function_abi_make_empty_table(target_id, triple, &ctx); authority = abi.mir_function_abi_table_with_function(authority, method_abi(target_id, triple, &ctx), &ctx);
    mut table := fat.mir_fat_pointer_make_empty_table(target_id, triple, &ctx); table = fat.mir_fat_pointer_table_with_call(table, selected_call(data.layout_id, metadata.layout_id, target_id, triple, &ctx), &ctx);
    mut validation := fat.mir_fat_pointer_abi_table_validate(table, layouts, authority, &ctx); if validation.valid == 0 { fail(std.Concat("Phase 16.7 fat pointer ABI rejected: ", validation.reason_code)); }
    mut request := fat.mir_serialize_fat_pointer_abi_for_request(table, layouts, authority, &ctx); mut witness := mir_to_c.mir_fat_pointer_abi_mir_to_c_witness(table, layouts, authority, &ctx);
    if os.WriteFile("/tmp/gust-phase16-fat-pointer-abi.request", request) == 0 || os.WriteFile("/tmp/gust-phase16-fat-pointer-abi.mir-to-c.witness", witness) == 0 { fail("Phase 16.7 could not write parity artifacts"); }
    os.LogStr("SUCCESS: Phase 16.7 fat pointer ABI smoke passed");
}
