import "mir_layout.gst" as layout;
import "mir_unsized_abi.gst" as unsized;
import "mir_unsized_abi_mir_to_c.gst" as mir_to_c;
import "mir_native_backend_unsized_abi_request.gst" as unsized_request;
func fail(message: str) { os.LogStr(message); os.Exit(1); }
func plan(id: str, value_id: str, form: str, position: str, owner: str, access_index: int, result: int, data_layout: str, element_layout: str, target: str, triple: str, ctx: &Arena) unsized.MirUnsizedAbiPlan[ctx] {
    mut value: unsized.MirUnsizedAbiPlan[ctx]; value.plan_id = std.Clone(ctx,id); value.value_id = std.Clone(ctx,value_id); value.form = std.Clone(ctx,form); value.position = std.Clone(ctx,position); value.transport = std.Clone(ctx,"fat_pointer_data_and_length"); value.data_id = std.Clone(ctx,std.Concat("data:",value_id)); value.data_type_id = std.Clone(ctx,"type:*i32_backing"); value.data_layout_id = std.Clone(ctx,data_layout); value.metadata_id = std.Clone(ctx,std.Concat("length:",value_id)); value.metadata_kind = std.Clone(ctx,"length_elements_u64"); value.metadata_present = 1; value.length_elements = 4; value.actual_length_elements = 4; value.element_type_id = std.Clone(ctx,"type:i32"); value.element_layout_id = std.Clone(ctx,element_layout); value.element_size = 4; value.checked_size_bytes = 16; value.actual_size_bytes = 16; value.overflow_checked = 1; value.required_alignment = 4; value.actual_alignment = 4; value.bounds_policy = std.Clone(ctx,"checked_index_less_than_length"); value.access_index = access_index; value.access_allowed = 1; value.storage_plan = std.Clone(ctx,"fixed_backing_explicit_borrowed_view"); value.storage_owner = std.Clone(ctx,owner); value.actual_storage_owner = std.Clone(ctx,owner); value.lifetime_id = std.Clone(ctx,std.Concat("lifetime:",value_id)); value.actual_lifetime_id = std.Clone(ctx,std.Concat("lifetime:",value_id)); value.operations = std.Clone(ctx,"bind_unsized_data,bind_length_metadata,checked_size_multiply,transport_unsized_view,bounds_check,read_element"); value.resource_disposition = std.Clone(ctx,"borrowed_no_transfer_state_live"); value.expected_value = result; value.actual_value = result; value.target_id = std.Clone(ctx,target); value.actual_target_id = std.Clone(ctx,target); value.target_triple = std.Clone(ctx,triple); value.actual_target_triple = std.Clone(ctx,triple); value.source_location = std.Clone(ctx,"compiler/phase16_unsized_value_source.gst:10:5"); return value;
}
func main() {
    mut ctx := os.Arena.New(); defer ctx.Free(); os.SetThreadScratch(ctx); mut target_id := "target:x86_64-unknown-linux-gnu"; mut triple := "x86_64-unknown-linux-gnu"; mut target := layout.mir_layout_make_target_v2(target_id,triple,"little",8,8,4,8,16,&ctx); mut layouts := layout.mir_layout_make_table(target,&ctx);
    mut data := layout.mir_layout_make_scalar_type_layout("type:*i32_backing",target_id,"pointer",8,8,64,"unsigned","any_bit_pattern",&ctx); mut element := layout.mir_layout_make_scalar_type_layout("type:i32",target_id,"integer",4,4,32,"signed","any_bit_pattern",&ctx); layouts = layout.mir_layout_table_with_layout(layouts,data,&ctx); layouts = layout.mir_layout_table_with_layout(layouts,element,&ctx);
    mut table := unsized.mir_unsized_make_empty_table(target_id,triple,&ctx); table = unsized.mir_unsized_table_with_plan(table,plan("unsized:param","slice:param","borrowed_slice_parameter","parameter","caller_borrowed_backing",1,11,data.layout_id,element.layout_id,target_id,triple,&ctx),&ctx); table = unsized.mir_unsized_table_with_plan(table,plan("unsized:result","slice:result","borrowed_slice_result","result","caller_backing_borrowed_result",2,21,data.layout_id,element.layout_id,target_id,triple,&ctx),&ctx); table = unsized.mir_unsized_table_with_plan(table,plan("unsized:local","slice:local","fixed_backing_local_slice_view","local_view","local_fixed_backing",3,31,data.layout_id,element.layout_id,target_id,triple,&ctx),&ctx);
    mut validation := unsized.mir_unsized_abi_table_validate(table,layouts,&ctx); if validation.valid == 0 { fail(std.Concat("Phase 16.8 unsized ABI rejected: ",validation.reason_code)); }
    mut request := unsized.mir_serialize_unsized_abi_for_request(table,layouts,&ctx); mut witness := mir_to_c.mir_unsized_abi_mir_to_c_witness(table,layouts,&ctx); if os.WriteFile("/tmp/gust-phase16-unsized-abi.request",request) == 0 || os.WriteFile("/tmp/gust-phase16-unsized-abi.mir-to-c.witness",witness) == 0 { fail("Phase 16.8 could not write parity artifacts"); }
    os.LogStr("SUCCESS: Phase 16.8 unsized ABI smoke passed");
}
