import "mir_layout.gst" as layout;
import "mir_dynamic_stack.gst" as dynamic_stack;
import "mir_dynamic_stack_mir_to_c.gst" as mir_to_c;
import "mir_native_backend_dynamic_stack_request.gst" as dynamic_request;
func fail(message: str) { os.LogStr(message); os.Exit(1); }
func plan(id: str, storage_id: str, form: str, scope: str, count: int, depth: int, exit_kind: str, result: int, element_layout: str, target: str, triple: str, ctx: &Arena) dynamic_stack.MirDynamicFramePlan[ctx] {
    mut value: dynamic_stack.MirDynamicFramePlan[ctx]; value.frame_plan_id = std.Clone(ctx,id); value.storage_id = std.Clone(ctx,storage_id); value.form = std.Clone(ctx,form); value.owning_function = std.Clone(ctx,"phase16_dynamic_stack_fixture"); value.owning_scope = std.Clone(ctx,scope); value.size_operand_id = std.Clone(ctx,std.Concat("size:",storage_id)); value.size_dominates = 1; value.element_layout_id = std.Clone(ctx,element_layout); value.element_size = 4; value.element_count = count; value.checked_size_bytes = count * 4; value.actual_size_bytes = count * 4; value.overflow_checked = 1; value.maximum_size_bytes = 4096; value.required_alignment = 4; value.actual_alignment = 4; value.zero_size_policy = std.Clone(ctx,"allow_zero_bytes_preserve_restore_marker"); value.nesting_depth = depth; value.lifetime_start = std.Clone(ctx,std.Concat("lifetime_start:",storage_id)); value.lifetime_end = std.Clone(ctx,std.Concat("lifetime_end:",storage_id)); value.restore_point = std.Clone(ctx,std.Concat("restore:",storage_id)); value.exit_kind = std.Clone(ctx,exit_kind); value.operations = std.Clone(ctx,"checked_dynamic_size>aligned_stack_allocate>lifetime_start>write_element>read_element>resource_cleanup>lifetime_end>restore_stack"); value.cleanup_order = std.Clone(ctx,"resource_cleanup_then_lifetime_end_then_stack_restore"); value.resource_cleanup_complete = 1; value.restoration_present = 1; value.restoration_after_cleanup = 1; value.use_within_lifetime = 1; value.expected_value = result; value.actual_value = result; value.target_id = std.Clone(ctx,target); value.actual_target_id = std.Clone(ctx,target); value.target_triple = std.Clone(ctx,triple); value.actual_target_triple = std.Clone(ctx,triple); value.source_location = std.Clone(ctx,"compiler/phase16_dynamic_stack_source.gst:10:5"); return value;
}
func main() {
    mut ctx := os.Arena.New(); defer ctx.Free(); os.SetThreadScratch(ctx); mut target_id := "target:x86_64-unknown-linux-gnu"; mut triple := "x86_64-unknown-linux-gnu"; mut target := layout.mir_layout_make_target_v2(target_id,triple,"little",8,8,4,8,16,&ctx); mut layouts := layout.mir_layout_make_table(target,&ctx); mut element := layout.mir_layout_make_scalar_type_layout("type:i32",target_id,"integer",4,4,32,"signed","any_bit_pattern",&ctx); layouts = layout.mir_layout_table_with_layout(layouts,element,&ctx);
    mut table := dynamic_stack.mir_dynamic_stack_make_empty_table(target_id,triple,&ctx); table = dynamic_stack.mir_dynamic_stack_table_with_plan(table,plan("frame:normal","storage:normal","bounded_vla_normal_exit","scope:function",4,0,"normal_return",41,element.layout_id,target_id,triple,&ctx),&ctx); table = dynamic_stack.mir_dynamic_stack_table_with_plan(table,plan("frame:early","storage:early","bounded_vla_early_return","scope:conditional",3,1,"early_return",31,element.layout_id,target_id,triple,&ctx),&ctx); table = dynamic_stack.mir_dynamic_stack_table_with_plan(table,plan("frame:nested","storage:nested","bounded_nested_vla","scope:nested",0,2,"normal_return",0,element.layout_id,target_id,triple,&ctx),&ctx);
    mut validation := dynamic_stack.mir_dynamic_stack_table_validate(table,layouts,&ctx); if validation.valid == 0 { fail(std.Concat("Phase 16.9 dynamic stack rejected: ",validation.reason_code)); }
    mut request := dynamic_stack.mir_serialize_dynamic_stack_for_request(table,layouts,&ctx); mut witness := mir_to_c.mir_dynamic_stack_mir_to_c_witness(table,layouts,&ctx); if os.WriteFile("/tmp/gust-phase16-dynamic-stack.request",request) == 0 || os.WriteFile("/tmp/gust-phase16-dynamic-stack.mir-to-c.witness",witness) == 0 { fail("Phase 16.9 could not write parity artifacts"); }
    os.LogStr("SUCCESS: Phase 16.9 dynamic stack smoke passed");
}
