// Phase 16.8 compiler-owned selected unsized value ABI.
import "mir_layout.gst" as layout;

type MirUnsizedAbiPlan[ctx] struct {
    plan_id: str, value_id: str, form: str, position: str, transport: str,
    data_id: str, data_type_id: str, data_layout_id: str,
    metadata_id: str, metadata_kind: str, metadata_present: int,
    length_elements: int, actual_length_elements: int,
    element_type_id: str, element_layout_id: str, element_size: int,
    checked_size_bytes: int, actual_size_bytes: int, overflow_checked: int,
    required_alignment: int, actual_alignment: int, bounds_policy: str,
    access_index: int, access_allowed: int, storage_plan: str,
    storage_owner: str, actual_storage_owner: str, lifetime_id: str,
    actual_lifetime_id: str, operations: str, resource_disposition: str,
    expected_value: int, actual_value: int, target_id: str,
    actual_target_id: str, target_triple: str, actual_target_triple: str,
    source_location: str
}
type MirUnsizedAbiTable[ctx] struct { format: str, target_id: str, target_triple: str, authority: str, size_policy: str, plans: Index[std.Vector[MirUnsizedAbiPlan[ctx], ctx], ctx] }
type MirUnsizedAbiValidation[ctx] struct { valid: int, reason_code: str }

func mir_unsized_empty_plans(ctx: &Arena) Index[std.Vector[MirUnsizedAbiPlan[ctx], ctx], ctx] { mut values: std.Vector[MirUnsizedAbiPlan[ctx], ctx] := std.VectorNew(ctx); mut index: Index[std.Vector[MirUnsizedAbiPlan[ctx], ctx], ctx] := os.ArenaAlloc(ctx); ctx.Set(index, values); return index; }
func mir_unsized_make_empty_table(target_id: str, target_triple: str, ctx: &Arena) MirUnsizedAbiTable[ctx] { mut table: MirUnsizedAbiTable[ctx]; table.format = std.Clone(ctx, "gust.compiler_unsized_abi.v1"); table.target_id = std.Clone(ctx, target_id); table.target_triple = std.Clone(ctx, target_triple); table.authority = std.Clone(ctx, "compiler_owned_unsized_data_metadata_storage_and_transport"); table.size_policy = std.Clone(ctx, "compiler_checked_length_times_element_size_no_backend_calculation"); table.plans = mir_unsized_empty_plans(ctx); return table; }
func mir_unsized_table_with_plan(table: MirUnsizedAbiTable[ctx], value: MirUnsizedAbiPlan[ctx], ctx: &Arena) MirUnsizedAbiTable[ctx] { mut updated := table; mut values: std.Vector[MirUnsizedAbiPlan[ctx], ctx] := ctx[updated.plans]; values.Push(value); ctx.Set(updated.plans, values); return updated; }
func mir_unsized_validation(valid: int, reason_code: str, ctx: &Arena) MirUnsizedAbiValidation[ctx] { mut result: MirUnsizedAbiValidation[ctx]; result.valid = valid; result.reason_code = std.Clone(ctx, reason_code); return result; }
func mir_unsized_layout_by_id(table: layout.MirLayoutTable[ctx], layout_id: str, ctx: &Arena) layout.MirTypeLayoutQuery[ctx] { mut result: layout.MirTypeLayoutQuery[ctx]; result.found = 0; mut values: std.Vector[layout.MirTypeLayout[ctx], ctx] := ctx[table.layouts]; mut index := 0; while index < len(values) { if std.str_eq(values[index].layout_id, layout_id) == 1 { result.found = 1; result.layout = values[index]; return result; } index = index + 1; } return result; }
func mir_unsized_form_valid(form: str, position: str) int { if std.str_eq(form, "borrowed_slice_parameter") == 1 && std.str_eq(position, "parameter") == 1 { return 1; } if std.str_eq(form, "borrowed_slice_result") == 1 && std.str_eq(position, "result") == 1 { return 1; } if std.str_eq(form, "fixed_backing_local_slice_view") == 1 && std.str_eq(position, "local_view") == 1 { return 1; } return 0; }

func mir_unsized_abi_table_validate(table: MirUnsizedAbiTable[ctx], layouts: layout.MirLayoutTable[ctx], ctx: &Arena) MirUnsizedAbiValidation[ctx] {
    if std.str_eq(table.format, "gust.compiler_unsized_abi.v1") == 0 { return mir_unsized_validation(0, "unsized_unknown_format", ctx); }
    if std.str_eq(table.authority, "compiler_owned_unsized_data_metadata_storage_and_transport") == 0 || std.str_eq(table.size_policy, "compiler_checked_length_times_element_size_no_backend_calculation") == 0 { return mir_unsized_validation(0, "unsized_backend_invented_size", ctx); }
    if layout.mir_layout_table_is_valid(layouts, ctx) == 0 || std.str_eq(table.target_id, layouts.target.target_id) == 0 || std.str_eq(table.target_triple, layouts.target.target_triple) == 0 || layouts.target.pointer_size != 8 { return mir_unsized_validation(0, "unsized_unsupported_target", ctx); }
    mut values: std.Vector[MirUnsizedAbiPlan[ctx], ctx] := ctx[table.plans]; mut index := 0;
    while index < len(values) {
        mut value := values[index]; if len(value.plan_id) == 0 || len(value.value_id) == 0 || mir_unsized_form_valid(value.form, value.position) == 0 { return mir_unsized_validation(0, "unsized_record_invalid", ctx); }
        if std.str_eq(value.transport, "fat_pointer_data_and_length") == 0 || len(value.storage_plan) == 0 { return mir_unsized_validation(0, "unsized_by_value_without_storage_plan", ctx); }
        if value.metadata_present != 1 || len(value.metadata_id) == 0 || std.str_eq(value.metadata_kind, "length_elements_u64") == 0 { return mir_unsized_validation(0, "unsized_missing_metadata", ctx); }
        if value.length_elements < 0 || value.length_elements > 8 || value.actual_length_elements != value.length_elements || value.element_size != 4 || value.checked_size_bytes != value.length_elements * value.element_size || value.actual_size_bytes != value.checked_size_bytes { return mir_unsized_validation(0, "unsized_inconsistent_length_or_layout", ctx); }
        if value.overflow_checked != 1 || std.str_find(value.operations, "checked_size_multiply") == 0 - 1 { return mir_unsized_validation(0, "unsized_size_overflow", ctx); }
        mut data_layout := mir_unsized_layout_by_id(layouts, value.data_layout_id, ctx); mut element_layout := mir_unsized_layout_by_id(layouts, value.element_layout_id, ctx); if data_layout.found == 0 || element_layout.found == 0 || std.str_eq(data_layout.layout.type_id, value.data_type_id) == 0 || std.str_eq(element_layout.layout.type_id, value.element_type_id) == 0 || data_layout.layout.size != 8 || element_layout.layout.size != value.element_size { return mir_unsized_validation(0, "unsized_inconsistent_length_or_layout", ctx); }
        if value.required_alignment != 4 || value.actual_alignment != value.required_alignment || element_layout.layout.alignment != value.required_alignment { return mir_unsized_validation(0, "unsized_insufficient_alignment", ctx); }
        if std.str_eq(value.bounds_policy, "checked_index_less_than_length") == 0 || value.access_index < 0 || value.access_index >= value.length_elements || value.access_allowed != 1 || std.str_find(value.operations, "bounds_check") == 0 - 1 { return mir_unsized_validation(0, "unsized_bounds_violation", ctx); }
        if len(value.storage_owner) == 0 || std.str_eq(value.storage_owner, value.actual_storage_owner) == 0 || len(value.lifetime_id) == 0 || std.str_eq(value.lifetime_id, value.actual_lifetime_id) == 0 { return mir_unsized_validation(0, "unsized_invalid_storage_ownership", ctx); }
        if std.str_eq(value.position, "result") == 1 && std.str_eq(value.storage_owner, "caller_backing_borrowed_result") == 0 { return mir_unsized_validation(0, "unsized_invalid_result_ownership", ctx); }
        if std.str_find(value.operations, "bind_unsized_data") == 0 - 1 || std.str_find(value.operations, "bind_length_metadata") == 0 - 1 || std.str_find(value.operations, "transport_unsized_view") == 0 - 1 { return mir_unsized_validation(0, "unsized_backend_invented_size", ctx); }
        if std.str_eq(value.resource_disposition, "borrowed_no_transfer_state_live") == 0 { return mir_unsized_validation(0, "unsized_resource_disposition_mismatch", ctx); }
        if value.expected_value != value.actual_value { return mir_unsized_validation(0, "unsized_value_mismatch", ctx); }
        if std.str_eq(value.target_id, table.target_id) == 0 || std.str_eq(value.actual_target_id, table.target_id) == 0 || std.str_eq(value.target_triple, table.target_triple) == 0 || std.str_eq(value.actual_target_triple, table.target_triple) == 0 { return mir_unsized_validation(0, "unsized_unsupported_target", ctx); }
        mut duplicate := index + 1; while duplicate < len(values) { if std.str_eq(values[duplicate].plan_id, value.plan_id) == 1 || std.str_eq(values[duplicate].value_id, value.value_id) == 1 { return mir_unsized_validation(0, "unsized_duplicate_identity", ctx); } duplicate = duplicate + 1; } index = index + 1;
    }
    return mir_unsized_validation(1, "unsized_abi_valid", ctx);
}
func mir_unsized_field(output: str, key: str, value: str, ctx: &Arena) str { mut result := std.Concat(output, key); result = std.Concat(result, "="); result = std.Concat(result, value); result = std.Concat(result, ";"); return std.Clone(ctx, result); }
func mir_serialize_unsized_abi_for_request(table: MirUnsizedAbiTable[ctx], layouts: layout.MirLayoutTable[ctx], ctx: &Arena) str {
    mut validation := mir_unsized_abi_table_validate(table, layouts, ctx); if validation.valid == 0 { mut invalid := "unsized_format: invalid\nunsized_reason: "; invalid = std.Concat(invalid, validation.reason_code); invalid = std.Concat(invalid, "\n"); return std.Clone(ctx, invalid); }
    mut values: std.Vector[MirUnsizedAbiPlan[ctx], ctx] := ctx[table.plans]; mut output := "unsized_format: gust.compiler_unsized_abi.v1\n"; output = std.Concat(output, "unsized_target_id: "); output = std.Concat(output, table.target_id); output = std.Concat(output, "\nunsized_target_triple: "); output = std.Concat(output, table.target_triple); output = std.Concat(output, "\nunsized_plan_count: "); output = std.Concat(output, std.FormatInt(len(values))); output = std.Concat(output, "\n");
    mut index := 0; while index < len(values) { mut v := values[index]; mut row := "unsized_plan:"; row = mir_unsized_field(row,"id",v.plan_id,ctx); row = mir_unsized_field(row,"value",v.value_id,ctx); row = mir_unsized_field(row,"form",v.form,ctx); row = mir_unsized_field(row,"position",v.position,ctx); row = mir_unsized_field(row,"transport",v.transport,ctx); row = mir_unsized_field(row,"data",v.data_id,ctx); row = mir_unsized_field(row,"data_type",v.data_type_id,ctx); row = mir_unsized_field(row,"data_layout",v.data_layout_id,ctx); row = mir_unsized_field(row,"metadata",v.metadata_id,ctx); row = mir_unsized_field(row,"metadata_kind",v.metadata_kind,ctx); row = mir_unsized_field(row,"metadata_present",std.FormatInt(v.metadata_present),ctx); row = mir_unsized_field(row,"length",std.FormatInt(v.length_elements),ctx); row = mir_unsized_field(row,"actual_length",std.FormatInt(v.actual_length_elements),ctx); row = mir_unsized_field(row,"element_type",v.element_type_id,ctx); row = mir_unsized_field(row,"element_layout",v.element_layout_id,ctx); row = mir_unsized_field(row,"element_size",std.FormatInt(v.element_size),ctx); row = mir_unsized_field(row,"checked_size",std.FormatInt(v.checked_size_bytes),ctx); row = mir_unsized_field(row,"actual_size",std.FormatInt(v.actual_size_bytes),ctx); row = mir_unsized_field(row,"overflow_checked",std.FormatInt(v.overflow_checked),ctx); row = mir_unsized_field(row,"required_alignment",std.FormatInt(v.required_alignment),ctx); row = mir_unsized_field(row,"actual_alignment",std.FormatInt(v.actual_alignment),ctx); row = mir_unsized_field(row,"bounds",v.bounds_policy,ctx); row = mir_unsized_field(row,"access_index",std.FormatInt(v.access_index),ctx); row = mir_unsized_field(row,"access_allowed",std.FormatInt(v.access_allowed),ctx); row = mir_unsized_field(row,"storage_plan",v.storage_plan,ctx); row = mir_unsized_field(row,"owner",v.storage_owner,ctx); row = mir_unsized_field(row,"actual_owner",v.actual_storage_owner,ctx); row = mir_unsized_field(row,"lifetime",v.lifetime_id,ctx); row = mir_unsized_field(row,"actual_lifetime",v.actual_lifetime_id,ctx); row = mir_unsized_field(row,"operations",v.operations,ctx); row = mir_unsized_field(row,"resource",v.resource_disposition,ctx); row = mir_unsized_field(row,"expected_value",std.FormatInt(v.expected_value),ctx); row = mir_unsized_field(row,"actual_value",std.FormatInt(v.actual_value),ctx); row = mir_unsized_field(row,"target",v.target_id,ctx); row = mir_unsized_field(row,"actual_target",v.actual_target_id,ctx); row = mir_unsized_field(row,"triple",v.target_triple,ctx); row = mir_unsized_field(row,"actual_triple",v.actual_target_triple,ctx); row = mir_unsized_field(row,"source",v.source_location,ctx); output = std.Concat(output,row); output = std.Concat(output,"\n"); index = index + 1; }
    return std.Clone(ctx, output);
}
