#!/usr/bin/env python3
"""Validate, render, and replay the Patch 24.0f CR-15 closure."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD_L1 = "guard-cranelift-phase24-cr15-close"
GUARD_L2 = "guard-cranelift-phase24-cr15-close-evidence"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
SCHEMA = ROOT / "scripts/cranelift_feature_registry.schema.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
VIEW = ROOT / "docs/PHASE24_CR15_CLOSURE.md"
ARCHITECTURE = ROOT / "docs/COMPILER_ARCHITECTURE_CONSOLIDATION.md"
SHARED_ZONE = ROOT / "docs/SHARED_SEMANTIC_ZONE.md"
JUSTFILE = ROOT / "justfile"
PR_FAST = ROOT / ".github/workflows/pr-fast.yml"
WORKFLOW = ROOT / ".github/workflows/phase24-cr15-closure.yml"
HISTORICAL_WORKFLOW = ROOT / ".github/workflows/cranelift-historical-full.yml"
SEED = ROOT / "gust_v4.c"

EXPECTED_PUBLICATIONS = [
    {
        "patch": "24.0a", "role": "roadmap_amendment", "pull_request": 301,
        "head_sha": "05e84b040a84eb2f79a3863d43dd3bbc678dca3e",
        "merge_main_sha": "8b84622ddffb88a97bd06d6b87e948d1e7e88545",
        "merged_at": "2026-09-02T13:35:12Z", "workflow_population": 100,
        "successful_workflows": 100, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0b", "role": "opening_authority", "pull_request": 302,
        "head_sha": "1496b69157227feab4cbcd21ff536385e418fdb5",
        "merge_main_sha": "da1889834f78853d685570cdbef70be77b9be06c",
        "merged_at": "2026-09-02T15:26:52Z", "workflow_population": 126,
        "successful_workflows": 126, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0c", "role": "generic_derivation", "pull_request": 303,
        "head_sha": "9d0b45ddb11dff6b1c98a8afc3f9c2315e3c6736",
        "merge_main_sha": "2383096a741c62e8de103a5b79281b9f616eb805",
        "merged_at": "2026-09-02T23:27:18Z", "workflow_population": 131,
        "successful_workflows": 131, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0d", "role": "cross_path_qualification", "pull_request": 306,
        "head_sha": "484b2b247924affb13afb05a75adf698077f18c6",
        "merge_main_sha": "10076805b56697304e7b236fff09cdf3689fcc05",
        "merged_at": "2026-09-03T02:24:01Z", "workflow_population": 131,
        "successful_workflows": 131, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0e", "role": "seed_identity_authority", "pull_request": 308,
        "head_sha": "48063f5c635d04b6c648fee09bc641e6b182e0eb",
        "merge_main_sha": "f1da52fdd0211414017d160d5bd55a2f12748530",
        "merged_at": "2026-09-03T04:16:55Z", "workflow_population": 104,
        "successful_workflows": 104, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0e", "role": "seed_publication_inventory", "pull_request": 309,
        "head_sha": "6f2e2a817defc3d1878789c04547ecdeb6a79031",
        "merge_main_sha": "d6cff02a66b8beaa4ff9798f33f9d57614dc817a",
        "merged_at": "2026-09-03T06:01:16Z", "workflow_population": 104,
        "successful_workflows": 104, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
    {
        "patch": "24.0e", "role": "generated_seed", "pull_request": 307,
        "head_sha": "49d4ec13a705e04e0b2c170b51cd45362c5ecdf8",
        "merge_main_sha": "aea95476d455c292f8b790a810b23bb98badcdd8",
        "merged_at": "2026-09-03T07:01:54Z", "workflow_population": 32,
        "successful_workflows": 32, "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    },
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"{GUARD_L1}: {message}")


def load() -> tuple[dict, dict]:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase24_cr15_closure")
    require(isinstance(closure, dict), "registry closure authority is missing")
    return registry, closure


def render(closure: dict) -> str:
    historical = closure["authoritative_historical_full"]
    budgets = closure["historical_budgets"]
    lines = [
        "# Phase 24.0f Closure — CR-15 Protected-Resource Guard Derivation",
        "",
        "<!-- Generated by scripts/phase24_cr15_closure.py from the Cranelift",
        "     feature registry. Do not edit by hand. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Exact merged publications",
        "",
        "| Patch | Role | PR | Exact head | Merge main | Workflows | Threads |",
        "| --- | --- | ---: | --- | --- | ---: | ---: |",
    ]
    for row in closure["implementation_publications"]:
        lines.append(
            f"| `{row['patch']}` | `{row['role']}` | #{row['pull_request']} | "
            f"`{row['head_sha']}` | `{row['merge_main_sha']}` | "
            f"{row['successful_workflows']}/{row['workflow_population']} | "
            f"{row['unresolved_non_outdated_review_threads']} |")
    lines += [
        "",
        "## Exact-main Historical authority",
        "",
        f"- Workflow/run: `{historical['workflow']}` / `{historical['run_id']}`",
        f"- Event: `{historical['event']}`",
        f"- Exact head: `{historical['head_sha']}`",
        f"- Conclusion: `{historical['conclusion']}`",
        f"- Jobs: `{historical['successful_jobs']}/{historical['total_jobs']}` successful",
        f"- Created/completed: `{historical['created_at']}` / `{historical['completed_at']}`",
        f"- Declared job timeout: `{budgets['job_timeout_minutes']}` minutes",
        f"- Historical/target max parallel: `{budgets['historical_shard_max_parallel']}` / `{budgets['target_matrix_max_parallel']}`",
        f"- Observed run/max-job/aggregate seconds: `{budgets['observed_run_wall_seconds']}` / `{budgets['observed_max_job_seconds']}` / `{budgets['observed_aggregate_job_seconds']}`",
        "",
        "## Compiler contract and handoff",
        "",
        "- Derivation is keyed only by resolved protected-Resource type and brand metadata.",
        "- The selected module-level contract remains `sync.lock` / `sync.get`.",
        "- Ordinary canonical MIR and existing cleanup/protected-access semantics are shared by MIR-to-C and Cranelift.",
        "- Cranelift remains explicit no-fallback; no Mutex or library-spelling backend special case exists.",
        "- General user-written generic functions remain closed.",
        f"- Seed: `{closure['bootstrap']['seed_digest']}` ({closure['bootstrap']['line_count']} lines), `{closure['bootstrap']['fixed_point']}`.",
        f"- Stdlib handoff: `{closure['stdlib_handoff']['status']}` for `S1.8-S1.11` after this closure PR is merged and current main is re-derived.",
        "",
        "Patch 24.1 is next. Phase 24 backend retirement, Phase 24.5, Phase 25, Web Slice 1, and Stdlib implementation remain outside this patch.",
        "",
    ]
    return "\n".join(lines)


def validate() -> dict:
    registry, closure = load()
    require(closure.get("contract_version") == "phase24_cr15_closure_v1",
            "contract version drifted")
    require(closure.get("status") ==
            "ready_for_merge_and_checked_post_merge_stdlib_handoff",
            "closure status drifted")
    require(closure.get("authority_base_main") ==
            "aea95476d455c292f8b790a810b23bb98badcdd8",
            "final implementation/seed main drifted")
    require(closure.get("next_patch") == "24.1", "next patch drifted")
    require(closure.get("implementation_publications") == EXPECTED_PUBLICATIONS,
            "merged publication evidence drifted")
    for row in EXPECTED_PUBLICATIONS:
        require(row["successful_workflows"] == row["workflow_population"] and
                row["unfinished_workflows"] == 0 and
                row["non_success_workflows"] == 0 and
                row["unresolved_non_outdated_review_threads"] == 0,
                f"publication #{row['pull_request']} is not fully qualified")

    expected_authorities = {
        "phase24_cr15_opening": ["phase24_cr15_opening_v1", "patch24_0b_complete_inert"],
        "phase24_cr15_derivation": ["phase24_cr15_derivation_v1", "patch24_0c_complete"],
        "phase24_cr15_qualification": ["phase24_cr15_qualification_v1", "patch24_0d_complete"],
    }
    require(closure.get("completed_authorities") == expected_authorities,
            "completed authority projection drifted")
    for key, (version, status) in expected_authorities.items():
        value = registry.get(key, {})
        require(value.get("contract_version") == version and
                value.get("status") == status,
                f"{key} is not complete")

    seed_digest = hashlib.sha256(SEED.read_bytes()).hexdigest()
    seed_lines = len(SEED.read_text(encoding="utf-8").splitlines())
    require(closure.get("bootstrap") == {
        "seed_path": "gust_v4.c",
        "seed_digest": seed_digest,
        "line_count": seed_lines,
        "fixed_point": "stage2_stage3_byte_identical",
        "publication_pr": 307,
        "bootstrap_route": "retained_explicit_mir_to_c_until_phase25",
    }, "bootstrap closure evidence drifted")
    seed_transition = registry["phase22_default_route_seed_convergence"][
        "phase24_cr15_seed_transition"]
    post_seed = seed_transition["accepted_live_seed_identities"][1]
    require(post_seed == {"state": "post_publication", "line_count": seed_lines,
                          "seed_digest": seed_digest},
            "live seed is not the registered CR-15 fixed point")

    historical = closure.get("authoritative_historical_full", {})
    require(historical == {
        "workflow": "Cranelift Historical Full",
        "run_id": 33726223959,
        "event": "workflow_dispatch",
        "head_branch": "main",
        "head_sha": "aea95476d455c292f8b790a810b23bb98badcdd8",
        "status": "completed",
        "conclusion": "success",
        "successful_jobs": 18,
        "total_jobs": 18,
        "unfinished_jobs": 0,
        "non_success_jobs": 0,
        "created_at": closure["authoritative_historical_full"].get("created_at"),
        "completed_at": closure["authoritative_historical_full"].get("completed_at"),
    }, "Historical Full authority drifted")
    require(historical["created_at"].endswith("Z") and
            historical["completed_at"].endswith("Z"),
            "Historical timestamps are not recorded")
    budgets = closure.get("historical_budgets", {})
    require(budgets.get("job_timeout_minutes") == 180 and
            budgets.get("historical_shard_max_parallel") == 4 and
            budgets.get("target_matrix_max_parallel") == 3 and
            all(isinstance(budgets.get(key), int) and budgets[key] > 0 for key in (
                "observed_run_wall_seconds", "observed_max_job_seconds",
                "observed_aggregate_job_seconds")),
            "Historical budgets are incomplete")

    task = TASK.read_text(encoding="utf-8")
    for row in (
        "- [x] Patch 24.0e — CR-15 Bootstrap Seed Reconvergence — DONE",
        "- [x] Patch 24.0f — CR-15 Closure and Stdlib Handoff — DONE",
    ):
        require(row in task, f"TASK status is missing {row}")
    require("- [ ] Patch 24.1 — Filename-Selected Behaviour Characterization" in task,
            "Patch 24.1 is not the next unchecked row")
    require("CR-15 is closed and handed off" in
            ARCHITECTURE.read_text(encoding="utf-8"),
            "architecture sequence does not record the checked handoff")
    require("Patch 24.0f closure/handoff" in
            SHARED_ZONE.read_text(encoding="utf-8"),
            "shared-zone handoff record is missing")

    require(closure.get("stdlib_handoff") == {
        "status": "effective_only_after_closure_pr_merge_and_current_main_rederivation",
        "unblocked_rows": ["S1.8", "S1.9", "S1.10", "S1.11"],
        "compiler_contract": "generic_backend_neutral_protected_Resource_guard_derivation",
        "stdlib_implementation_owned_by": "Stdlib lane",
        "task_stdlib_edited_by_this_patch": False,
    }, "Stdlib handoff boundary drifted")
    require(closure.get("boundary") == {
        "changes_accepted_Gust_meaning": False,
        "adds_or_changes_MIR_operations": False,
        "changes_ABI_layout_runtime_symbols_target_or_linker": False,
        "changes_backend_route_default_or_fallback": False,
        "changes_bootstrap_route_or_seed": False,
        "edits_stdlib": False,
        "begins_patch24_1_or_backend_retirement": False,
    }, "closure boundary drifted")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    require(levels.get(GUARD_L1) == 1 and levels.get(GUARD_L2) == 2,
            "test-level assignments drifted")
    just = JUSTFILE.read_text(encoding="utf-8")
    require(f"{GUARD_L1}:" in just and f"{GUARD_L2}:" in just,
            "just reachability drifted")
    require(GUARD_L1 in PR_FAST.read_text(encoding="utf-8"),
            "PR Fast does not own closure validation")
    workflow = WORKFLOW.read_text(encoding="utf-8")
    for token in ("pull_request:", "push:", "workflow_dispatch:", GUARD_L1,
                  GUARD_L2, "gust_v4.c", "compiler/*.gst", "src/runtime.c",
                  "src/runtime/**", "tools/normalize_generated_arena_offsets.py"):
        require(token in workflow, f"closure workflow is missing {token}")
    historical_workflow = HISTORICAL_WORKFLOW.read_text(encoding="utf-8")
    require(historical_workflow.count("timeout-minutes: 180") == 5 and
            "max-parallel: 4" in historical_workflow and
            "max-parallel: 3" in historical_workflow,
            "Historical declared budgets drifted")
    require(VIEW.read_text(encoding="utf-8") == render(closure),
            "generated closure view is stale; run render")
    return closure


def replay(command: list[str], timeout: int) -> None:
    result = subprocess.run(command, cwd=ROOT, timeout=timeout, check=False)
    require(result.returncode == 0, f"evidence command failed: {' '.join(command)}")


def evidence() -> None:
    validate()
    replay(["make", "gust"], 900)
    replay(["make", "phase10-native-package"], 900)
    replay(["just", "guard-cranelift-phase24-cr15-opening-evidence"], 900)
    replay(["just", "guard-cranelift-phase24-cr15-qualification-evidence"], 1800)
    replay(["python3", "scripts/phase23_production_release_audit.py", "evidence"], 1800)
    replay(["python3", "scripts/phase22_default_route_seed_convergence.py",
            "check-regeneration"], 900)
    replay(["make", "bootstrap"], 1800)
    replay(["just", "guard-cranelift-registry-schema"], 300)
    replay(["just", "guard-cranelift-registry-projection"], 300)
    replay(["just", "guard-cranelift-ci-family-projection"], 300)
    replay(["just", "guard-ci-guard-reachability"], 300)
    replay(["just", "guard-ci-fixture-reachability"], 300)
    validate()
    print("phase24_cr15_closure: evidence ok")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("validate", "render", "check-review", "evidence"))
    args = parser.parse_args()
    if args.command == "render":
        _, closure = load()
        VIEW.write_text(render(closure), encoding="utf-8")
        validate()
        print("phase24_cr15_closure: render ok")
    elif args.command == "evidence":
        evidence()
    else:
        validate()
        print("phase24_cr15_closure: review current" if args.command == "check-review"
              else "phase24_cr15_closure: ok")


if __name__ == "__main__":
    main()
