#!/usr/bin/env python3
"""Validate and render the Patch 23.15 Phase 23 closure statement."""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase23-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
VIEW = ROOT / "docs/PHASE23_CLOSURE.md"
JUSTFILE = ROOT / "justfile"
PR_FAST = ROOT / ".github/workflows/pr-fast.yml"
CONTRACT = ROOT / "tests/cranelift/phase23_closure_contract.tsv"
WORKFLOW = ROOT / ".github/workflows/phase23-close.yml"

EXPECTED_PATCHES = [
    "23.0", "23.1", "23.2", "23.3", "23.3a", "23.4", "23.5",
    "23.6", "23.6a", "23.7", "23.8", "23.8a", "23.9", "23.10",
    "23.11", "23.12", "23.13", "23.14", "23.15",
]

EXPECTED_AUTHORITIES = {
    "phase23_issue_health_opening": ("phase23_issue_health_opening_v1", "patch23_1_complete"),
    "phase23_mir_evidence_owner": ("phase23_mir_evidence_owner_v1", "closed_on_merged_current_main"),
    "phase23_resource_acquisition_parity": ("phase23_resource_acquisition_parity_v1", "closed_on_merged_current_main"),
    "phase23_structured_guard_defer_native_admission": ("phase23_structured_guard_defer_native_admission_v1", "patch23_3a_complete"),
    "phase23_assurance_phase_a": ("phase23_assurance_phase_a_v1", "phase23_4_complete_report_only"),
    "phase23_assurance_phase_b": ("phase23_assurance_phase_b_v1", "phase23_5_complete_report_only"),
    "phase23_same_scope_declaration": ("phase23_same_scope_declaration_v1", "closed_on_merged_current_main"),
    "phase23_mir_to_c_deprecation_opening": ("phase23_mir_to_c_deprecation_opening_v1", "patch23_7_complete"),
    "phase23_mir_to_c_frozen_surface": ("phase23_mir_to_c_frozen_surface_v1", "patch23_9_complete"),
    "phase23_mir_to_c_focused_live": ("phase23_mir_to_c_focused_live_v1", "patch23_10_complete"),
    "phase23_mir_to_c_archived_corpus": ("phase23_mir_to_c_archived_corpus_v1", "patch23_11_complete"),
    "phase23_production_release_audit": ("phase23_production_release_audit_v1", "patch23_12_complete"),
    "phase23_cross_feature_qualification": ("phase23_cross_feature_qualification_v1", "patch23_13_complete"),
    "phase23_historical_full_qualification": ("phase23_historical_full_qualification_v1", "patch23_14_complete"),
}


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    require(spec is not None and spec.loader is not None,
            f"cannot load {path.relative_to(ROOT)}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def event_paths(workflow: str, event: str, next_event: str) -> str:
    start_marker = f"  {event}:"
    end_marker = f"  {next_event}:"
    require(start_marker in workflow and end_marker in workflow,
            f"workflow has no bounded {event} filter")
    return workflow.split(start_marker, 1)[1].split(end_marker, 1)[0]


def live_inventory() -> dict[str, object]:
    path = ROOT / "scripts/phase23_mir_to_c_deprecation_opening.py"
    spec = importlib.util.spec_from_file_location("phase23_closure_inventory", path)
    require(spec is not None and spec.loader is not None,
            "cannot load the Phase 23 consumer scanner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.inventory_summary()


def live_frozen_surface(registry: dict) -> dict[str, object]:
    path = ROOT / "scripts/phase23_mir_to_c_frozen_surface.py"
    spec = importlib.util.spec_from_file_location("phase23_closure_frozen", path)
    require(spec is not None and spec.loader is not None,
            "cannot load the Phase 23 frozen-surface scanner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.scan(registry)["live_c_case_surface"]


def render(closure: dict) -> str:
    historical = closure["authoritative_latest_historical_full"]
    budgets = closure["historical_budgets"]
    route = closure["route_authority"]
    compatibility = closure["compatibility_authority"]
    production = closure["production_release_authority"]
    bootstrap = closure["bootstrap_authority"]
    lines = [
        "# Phase 23 Closure — MIR-to-C Deprecation",
        "",
        "<!-- Generated by scripts/phase23_closure.py from the Cranelift feature",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Authoritative closure gate",
        "",
        f"- Workflow/run: `{historical['workflow']}` / `{historical['run_id']}`",
        f"- Event: `{historical['event']}`",
        f"- Exact final implementation head: `{historical['head_sha']}`",
        f"- Conclusion: `{historical['conclusion']}`",
        f"- Jobs: `{historical['successful_jobs']}/{historical['total_jobs']}` successful",
        f"- Run/max-job/aggregate seconds: `{budgets['observed_run_wall_seconds']}/{budgets['observed_max_job_seconds']}/{budgets['observed_aggregate_job_seconds']}`",
        "",
        "## Backend and evidence routes",
        "",
        f"- Default/explicit native: `{route['default_backend']}` / `{route['explicit_native_backend']}`",
        "- Deprecated explicit C spellings: " +
        ", ".join(f"`{item}`" for item in route["explicit_c_spellings"]),
        f"- Fallback: `{route['fallback']}`",
        f"- Focused non-bootstrap live lanes: `{compatibility['focused_non_bootstrap_live_lanes']}`",
        f"- Archived corpus cases: `{compatibility['archived_case_count']}`",
        f"- Supported production/release requires MIR-to-C: `{str(production['supported_production_or_release_requires_mir_to_c']).lower()}`",
        "",
        "## Bootstrap boundary",
        "",
        f"- Route: `{bootstrap['route']}`",
        f"- Explicit C callers: `{bootstrap['explicit_c_callers']}`",
        f"- Seed: `{bootstrap['seed']}`",
        f"- Fixed point: `{bootstrap['fixed_point']}`",
        f"- Owning phase: `{bootstrap['owner_phase']}`",
        "",
        "## What Phase 23 does not claim",
        "",
    ]
    lines += [f"- {claim}" for claim in closure["non_claims"]]
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase23_closure")
    require(isinstance(closure, dict), "closure authority missing")
    require(closure.get("version") == "phase23_closure_v1",
            "closure version drifted")
    require(closure.get("status") ==
            "phase23_closed_mir_to_c_deprecated_production_native_bootstrap_c_preserved",
            "closure status drifted")
    require(closure.get("authority_owner") ==
            "scripts/cranelift_feature_registry.json", "closure owner drifted")

    completed = {}
    for key, (version, status) in EXPECTED_AUTHORITIES.items():
        authority = registry.get(key)
        require(isinstance(authority, dict), f"required authority {key} is absent")
        actual_version = authority.get("contract_version") or authority.get("version")
        require(actual_version == version and authority.get("status") == status,
                f"{key} version or status drifted")
        completed[key] = version
    require(closure.get("completed_authorities") == completed,
            "completed authority projection drifted")

    task = TASK.read_text(encoding="utf-8")
    active = task.split("# Immutable Phase 22 Completion Record", 1)[0]
    rows = re.findall(r"^- \[([ x])\] Patch (23\.\d+[a-z]?) — .+$",
                      active, re.MULTILINE)
    require([patch for _, patch in rows] == EXPECTED_PATCHES,
            "Phase 23 status rows are missing, duplicated, or reordered")
    lines = re.findall(r"^- \[[ x]\] Patch 23\.\d+[a-z]? — .+$",
                       active, re.MULTILINE)
    require(all(mark == "x" and line.endswith(" — DONE")
                for (mark, _), line in zip(rows, lines)),
            "every Phase 23 status row must be DONE")
    require("## Phase 23 Closure Record" in task,
            "TASK.md does not record Phase 23 closure")

    predecessor = closure.get("predecessor_review_gate", {})
    require(predecessor == {
        "pull_request": 297,
        "head_sha": "b646bd4b84b8b804910880c4efed8b7831d31e87",
        "merge_main_sha": "8985a3d09b1f119accd12cd952940ef019d6a698",
        "merged_at": "2026-09-02T06:06:43Z",
        "event": "pull_request",
        "successful_workflows": 124,
        "total_workflows": 124,
        "unfinished_workflows": 0,
        "non_success_workflows": 0,
        "unresolved_non_outdated_review_threads": 0,
    }, "Patch 23.14 merge or review evidence drifted")

    historical_authority = registry["phase23_historical_full_qualification"]
    require(closure.get("authoritative_latest_historical_full") ==
            historical_authority["authoritative_historical_full"],
            "Historical closure evidence does not project Patch 23.14")
    require(closure.get("historical_budgets") ==
            historical_authority["elapsed_budgets"],
            "Historical elapsed budgets drifted")
    historical = closure["authoritative_latest_historical_full"]
    require(historical["status"] == historical["conclusion"] == "success" or
            (historical["status"] == "completed" and
             historical["conclusion"] == "success"),
            "Historical Full is not completed success")
    require(historical["successful_jobs"] == historical["total_jobs"] == 18 and
            historical["unfinished_jobs"] == historical["non_success_jobs"] == 0,
            "Historical Full job population is incomplete")
    require(historical["head_sha"] ==
            historical_authority["final_implementation_review_gate"]["merged_main_sha"],
            "Historical Full is not on exact final implementation main")

    for issue, key in ((105, "phase23_same_scope_declaration"),
                       (110, "phase23_mir_evidence_owner"),
                       (240, "phase23_resource_acquisition_parity")):
        authority = registry[key]
        require(authority.get("issue") == issue and
                authority.get("status") == "closed_on_merged_current_main" and
                authority.get("issue_closure", {}).get("issue_state") == "closed",
                f"issue #{issue} is not closed on merged current-main evidence")
    require(closure.get("issue_closure") == {
        "issues": [105, 110, 240],
        "state": "closed_on_merged_current_main_evidence",
    }, "issue closure summary drifted")

    deprecation = registry["phase23_mir_to_c_deprecation_opening"]["deprecation_contract"]
    route = closure.get("route_authority", {})
    require(route == {
        "default_backend": "cranelift",
        "explicit_native_backend": "cranelift",
        "explicit_c_spellings": ["mir-to-c", "c"],
        "explicit_c_acceptance": "deprecated_byte_identical_through_phase23",
        "fallback": "forbidden",
        "backend_removal_phase": "24",
        "bootstrap_c_retirement_phase": "25",
    }, "closure route authority drifted")
    require(route["explicit_c_spellings"] ==
            deprecation["route_contract"]["explicit_c_spellings"] and
            route["fallback"] == deprecation["route_contract"]["fallback"],
            "deprecation and closure route authorities disagree")

    focused = registry["phase23_mir_to_c_focused_live"]
    archive = registry["phase23_mir_to_c_archived_corpus"]
    frozen = registry["phase23_cross_feature_qualification"]["frozen_surface_transition"]
    require(closure.get("compatibility_authority") == {
        "focused_non_bootstrap_live_lanes": 1,
        "focused_lane": focused["contract_version"],
        "archived_corpus": archive["contract_version"],
        "archived_case_count": archive["case_count"],
        "frozen_live_c_cases": frozen["current_live_c_case_surface"]["count"],
    }, "focused/archive/frozen closure projection drifted")

    frozen_transition = closure.get("frozen_surface_transition", {})
    derivation_frozen_transition = registry.get(
        "phase24_cr15_derivation", {}).get("frozen_surface_transition")
    previous_frozen = frozen["current_live_c_case_surface"]
    frozen_unchanged = [
        "count", "case_id_manifest_digest", "owner_contract_count",
        "owner_counts", "consumer_class_counts", "selection_counts",
    ]
    require(frozen_transition.get("contract_version") ==
            "phase23_closure_frozen_surface_transition_v1" and
            frozen_transition.get("status") == "patch23_15_complete" and
            frozen_transition.get("authority_base_main") ==
            predecessor["merge_main_sha"] and
            frozen_transition.get("previous_live_c_case_surface") ==
            previous_frozen and
            frozen_transition.get("current_live_c_case_surface") ==
            (live_frozen_surface(registry)
             if derivation_frozen_transition is None else
             derivation_frozen_transition.get("previous_live_c_case_surface")) and
            frozen_transition.get("unchanged_fields") == frozen_unchanged and
            frozen_transition.get("change_reason") ==
            "closure_authority_and_workflow_wiring_shifted_command_lines_and_owner_file_digests_without_changing_the_frozen_explicit_C_case_population" and
            frozen_transition.get("partial_or_unregistered_surface") == "rejected",
            "closure frozen-surface transition drifted")
    for field in frozen_unchanged:
        require(frozen_transition["current_live_c_case_surface"].get(field) ==
                previous_frozen.get(field),
                f"closure changed frozen explicit-C field: {field}")
    if derivation_frozen_transition is not None:
        current_frozen = live_frozen_surface(registry)
        require(
            derivation_frozen_transition.get("contract_version") ==
            "phase24_cr15_derivation_frozen_surface_transition_v1" and
            derivation_frozen_transition.get("status") == "patch24_0c_complete" and
            derivation_frozen_transition.get("authority_base_main") ==
            "c37024afa580d1e03c5ff70150ed0ae7518a9648" and
            derivation_frozen_transition.get("previous_live_c_case_surface") ==
            frozen_transition["current_live_c_case_surface"] and
            derivation_frozen_transition.get("current_live_c_case_surface") ==
            current_frozen and
            derivation_frozen_transition.get("unchanged_fields") ==
            frozen_unchanged and
            derivation_frozen_transition.get("change_reason") ==
            "CR15_derivation_preserved_the_frozen_explicit_C_case_population_through_exact_relay_projection" and
            derivation_frozen_transition.get("partial_or_unregistered_surface") ==
            "rejected",
            "Patch 24.0c frozen-surface closure successor drifted")
        for field in frozen_unchanged:
            require(current_frozen.get(field) ==
                    derivation_frozen_transition[
                        "previous_live_c_case_surface"].get(field),
                    f"Patch 24.0c changed frozen explicit-C field: {field}")

    production = registry["phase23_production_release_audit"]
    require(closure.get("production_release_authority") == {
        "authority": production["contract_version"],
        "supported_production_or_release_requires_mir_to_c": False,
        "remaining_live_c_owners": ["phase23_mir_to_c_focused_live", "phase25_bootstrap"],
    }, "production and release closure projection drifted")
    require(production["route_contract"][
        "supported_production_or_release_requires_mir_to_c"] is False,
        "a supported production or release route still requires MIR-to-C")
    production_transition = closure.get("production_audit_transition", {})
    derivation_production_transition = registry.get(
        "phase24_cr15_derivation", {}).get("production_audit_transition")
    production_unchanged = [
        "supported_surface_count", "repository_invocation_count",
        "repository_explicit_c_count", "phase25_bootstrap_explicit_c_count",
        "non_bootstrap_retained_test_surface_count",
        "supported_production_or_release_explicit_c_count",
        "active_non_bootstrap_live_c_lane_count",
        "active_non_bootstrap_live_c_owner", "unknown_downstream_count",
    ]
    production_module_path = ROOT / "scripts/phase23_production_release_audit.py"
    production_spec = importlib.util.spec_from_file_location(
        "phase23_closure_production", production_module_path)
    require(production_spec is not None and production_spec.loader is not None,
            "cannot load the Phase 23 production audit")
    production_module = importlib.util.module_from_spec(production_spec)
    production_spec.loader.exec_module(production_module)
    require(production_transition.get("contract_version") ==
            "phase23_closure_production_audit_transition_v1" and
            production_transition.get("status") == "patch23_15_complete" and
            production_transition.get("authority_base_main") ==
            predecessor["merge_main_sha"] and
            production_transition.get("previous_audit") == production["audit"] and
            production_transition.get("current_audit") ==
            (production_module.scan()
             if derivation_production_transition is None else
             derivation_production_transition.get("previous_audit")) and
            production_transition.get("unchanged_fields") ==
            production_unchanged and
            production_transition.get("change_reason") ==
            "closure_status_and_guard_wiring_changed_supported_surface_file_digests_without_changing_routes_or_counts" and
            production_transition.get("partial_extra_or_substituted_audit") ==
            "rejected",
            "closure production audit transition drifted")
    for field in production_unchanged:
        require(production_transition["current_audit"].get(field) ==
                production_transition["previous_audit"].get(field),
                f"closure changed production audit field: {field}")
    if derivation_production_transition is not None:
        current_audit = production_module.scan()
        require(
            derivation_production_transition.get("contract_version") ==
            "phase24_cr15_derivation_production_audit_transition_v1" and
            derivation_production_transition.get("status") ==
            "patch24_0c_complete" and
            derivation_production_transition.get("authority_base_main") ==
            "c37024afa580d1e03c5ff70150ed0ae7518a9648" and
            derivation_production_transition.get("previous_audit") ==
            production_transition["current_audit"] and
            derivation_production_transition.get("current_audit") ==
            current_audit and
            derivation_production_transition.get("unchanged_fields") ==
            production_unchanged and
            derivation_production_transition.get("change_reason") ==
            "CR15_derivation_preserved_the_production_audit_through_exact_relay_projection" and
            derivation_production_transition.get(
                "partial_extra_or_substituted_audit") == "rejected",
            "Patch 24.0c production-audit closure successor drifted")
        for field in production_unchanged:
            require(current_audit.get(field) ==
                    derivation_production_transition["previous_audit"].get(field),
                    f"Patch 24.0c changed production audit field: {field}")

    require(closure.get("bootstrap_authority") == {
        "route": "explicit_mir_to_c_and_host_c",
        "explicit_c_callers": 5,
        "seed": "gust_v4.c",
        "fixed_point": "stage2_stage3_byte_identity",
        "owner_phase": "25",
    }, "Phase 25 bootstrap boundary drifted")

    transition = closure.get("consumer_inventory_transition", {})
    previous = historical_authority["consumer_inventory_transition"]["current_inventory"]
    roadmap_transition = closure.get(
        "phase24_opening_preflight_roadmap_transition")
    cr15_roadmap_transition = closure.get(
        "phase24_cr15_roadmap_amendment_transition")
    cr15_opening_transition = closure.get(
        "phase24_cr15_opening_transition")
    cr15_derivation_transition = registry.get(
        "phase24_cr15_derivation", {}).get("consumer_inventory_transition")
    cr15_qualification_transition = registry.get(
        "phase24_cr15_qualification", {}).get("consumer_inventory_transition")
    cr15_seed_transition = registry.get(
        "phase24_cr15_seed_authority_consumer_transition")
    cr15_seed_publication = (
        cr15_seed_transition.get("seed_publication_transition")
        if isinstance(cr15_seed_transition, dict) else None
    )
    cr15_closure_transition = registry.get(
        "phase24_cr15_closure", {}).get("consumer_inventory_transition")
    closure_current = (
        roadmap_transition.get("previous_inventory")
        if isinstance(roadmap_transition, dict) else live_inventory()
    )
    unchanged = [
        "invocation_count", "invocation_manifest_digest",
        "structural_surface_count", "structural_manifest_digest",
        "invocation_selection_counts", "unclassified_count",
    ]
    require(transition.get("contract_version") ==
            "phase23_closure_consumer_inventory_transition_v1" and
            transition.get("status") == "patch23_15_complete" and
            transition.get("authority_base_main") == predecessor["merge_main_sha"] and
            transition.get("previous_inventory") == previous and
            transition.get("current_inventory") == closure_current and
            transition.get("unchanged_fields") == unchanged and
            transition.get("partial_extra_or_substituted_surface") == "rejected",
            "closure consumer inventory transition drifted")
    for field in unchanged:
        require(transition["current_inventory"].get(field) == previous.get(field),
                f"closure changed consumer inventory field: {field}")
    added = transition.get("registered_added_paths", [])
    require([row.get("path") for row in
             transition.get("registered_added_text_surfaces", [])] == added,
            "closure added-text manifest path order drifted")
    if isinstance(roadmap_transition, dict):
        roadmap_unchanged = [
            "text_surface_count", "invocation_count",
            "invocation_manifest_digest", "structural_surface_count",
            "structural_manifest_digest", "classification_counts",
            "invocation_selection_counts", "unclassified_count",
        ]
        require(
            roadmap_transition.get("contract_version") ==
            "phase24_opening_preflight_roadmap_transition_v1" and
            roadmap_transition.get("status") == "patch24_0_complete" and
            roadmap_transition.get("authority_base_main") ==
            "1c5e7fe5dee11aa00019bffafe14778a449b96d4" and
            roadmap_transition.get("previous_inventory") ==
            transition["current_inventory"] and
            roadmap_transition.get("current_inventory") ==
            (live_inventory() if cr15_roadmap_transition is None else
             cr15_roadmap_transition.get("previous_inventory")) and
            roadmap_transition.get("registered_changed_paths") ==
            ["TASK.md", "scripts/phase23_closure.py"] and
            roadmap_transition.get("unchanged_fields") == roadmap_unchanged and
            roadmap_transition.get(
                "partial_extra_or_substituted_surface") == "rejected",
            "Patch 24.0 roadmap consumer inventory transition drifted")
        for field in roadmap_unchanged:
            require(roadmap_transition["current_inventory"].get(field) ==
                    roadmap_transition["previous_inventory"].get(field),
                    f"Patch 24.0 changed consumer inventory field: {field}")
        if isinstance(cr15_roadmap_transition, dict):
            require(
                cr15_roadmap_transition.get("contract_version") ==
                "phase24_cr15_roadmap_amendment_transition_v1" and
                cr15_roadmap_transition.get("status") == "patch24_0a_complete" and
                cr15_roadmap_transition.get("authority_base_main") ==
                "86d13496fa83c6d3688402f09b77a8dfbb8168fc" and
                cr15_roadmap_transition.get("previous_inventory") ==
                roadmap_transition["current_inventory"] and
                cr15_roadmap_transition.get("current_inventory") ==
                (live_inventory() if cr15_opening_transition is None else
                 cr15_opening_transition.get("previous_inventory")) and
                cr15_roadmap_transition.get("registered_changed_paths") ==
                ["TASK.md", "scripts/phase23_closure.py"] and
                cr15_roadmap_transition.get("previous_changed_text_surfaces") ==
                roadmap_transition["current_changed_text_surfaces"] and
                cr15_roadmap_transition.get("unchanged_fields") ==
                roadmap_unchanged and
                cr15_roadmap_transition.get(
                    "partial_extra_or_substituted_surface") == "rejected",
                "Patch 24.0a CR-15 roadmap consumer transition drifted")
            for field in roadmap_unchanged:
                require(cr15_roadmap_transition["current_inventory"].get(field) ==
                        roadmap_transition["current_inventory"].get(field),
                        f"Patch 24.0a changed consumer inventory field: {field}")
            module = load_module(
                "phase23_deprecation_successor",
                ROOT / "scripts/phase23_mir_to_c_deprecation_opening.py",
            )
            changed_paths = ["TASK.md", "scripts/phase23_closure.py"]
            live_rows = module.scan_text_surfaces()
            changed_rows = [row for row in live_rows
                            if row["path"] in changed_paths]
            if cr15_opening_transition is None:
                require([row["path"] for row in changed_rows] == changed_paths and
                        cr15_roadmap_transition.get(
                            "current_changed_text_surfaces") == changed_rows,
                        "Patch 24.0a changed surface identity drifted")
                require(module.canonical_digest([
                    row for row in live_rows if row["path"] not in changed_paths
                ]) == cr15_roadmap_transition.get(
                    "unchanged_other_text_surface_manifest_digest"),
                    "Patch 24.0a changed an unregistered text surface")
            else:
                require(
                    cr15_opening_transition.get("contract_version") ==
                    "phase24_cr15_opening_transition_v1" and
                    cr15_opening_transition.get("status") ==
                    "patch24_0b_complete_inert" and
                    cr15_opening_transition.get("authority_base_main") ==
                    "8b84622ddffb88a97bd06d6b87e948d1e7e88545" and
                    cr15_opening_transition.get("previous_inventory") ==
                    cr15_roadmap_transition["current_inventory"] and
                    cr15_opening_transition.get("current_inventory") ==
                    (live_inventory() if cr15_derivation_transition is None else
                     cr15_derivation_transition.get("previous_inventory")) and
                    cr15_opening_transition.get("registered_changed_paths") ==
                    changed_paths and
                    cr15_opening_transition.get("previous_changed_text_surfaces") ==
                    cr15_roadmap_transition["current_changed_text_surfaces"] and
                    cr15_opening_transition.get("unchanged_fields") ==
                    roadmap_unchanged and
                    cr15_opening_transition.get(
                        "partial_extra_or_substituted_surface") == "rejected",
                    "Patch 24.0b CR-15 opening consumer transition drifted")
                if cr15_derivation_transition is None:
                    require([row["path"] for row in changed_rows] == changed_paths and
                            cr15_opening_transition.get(
                                "current_changed_text_surfaces") == changed_rows,
                            "Patch 24.0b changed surface identity drifted")
                    require(module.canonical_digest([
                        row for row in live_rows if row["path"] not in changed_paths
                    ]) == cr15_opening_transition.get(
                        "unchanged_other_text_surface_manifest_digest"),
                        "Patch 24.0b changed an unregistered text surface")
                else:
                    successor_unchanged = [
                        "invocation_count", "invocation_manifest_digest",
                        "structural_surface_count", "structural_manifest_digest",
                        "invocation_selection_counts", "unclassified_count",
                    ]
                    successor_paths = cr15_derivation_transition.get(
                        "registered_changed_paths", [])
                    successor_rows = (
                        [row for row in live_rows
                         if row["path"] in successor_paths]
                        if cr15_qualification_transition is None else
                        cr15_derivation_transition.get(
                            "current_changed_text_surfaces", [])
                    )
                    successor_other_digest = (
                        module.canonical_digest([
                            row for row in live_rows
                            if row["path"] not in successor_paths
                        ])
                        if cr15_qualification_transition is None else
                        cr15_derivation_transition.get(
                            "unchanged_other_text_surface_manifest_digest")
                    )
                    current = live_inventory()
                    derivation_current = (
                        current if cr15_qualification_transition is None
                        else cr15_derivation_transition["current_inventory"]
                    )
                    require(
                        cr15_derivation_transition.get("contract_version") ==
                        "phase24_cr15_derivation_consumer_transition_v1" and
                        cr15_derivation_transition.get("status") ==
                        "patch24_0c_complete" and
                        cr15_derivation_transition.get("authority_base_main") ==
                        "c37024afa580d1e03c5ff70150ed0ae7518a9648" and
                        cr15_derivation_transition.get("previous_inventory") ==
                        cr15_opening_transition["current_inventory"] and
                        cr15_derivation_transition.get("current_inventory") ==
                        (current if cr15_qualification_transition is None else
                         cr15_qualification_transition.get("previous_inventory")) and
                        cr15_derivation_transition.get("unchanged_fields") ==
                        successor_unchanged and
                        derivation_current.get("text_surface_count") ==
                        cr15_derivation_transition["previous_inventory"].get(
                            "text_surface_count") + 1 and
                        derivation_current.get("classification_counts", {}).get(
                            "archive_candidate") ==
                        cr15_derivation_transition["previous_inventory"].get(
                            "classification_counts", {}).get(
                                "archive_candidate") + 1 and
                        all(derivation_current.get(
                                "classification_counts", {}).get(key) ==
                            cr15_derivation_transition["previous_inventory"].get(
                                "classification_counts", {}).get(key)
                            for key in (
                                "bootstrap_phase25", "focused_live_oracle",
                                "historical_only", "production_or_release_migration",
                            )) and
                        cr15_derivation_transition.get(
                            "partial_extra_or_substituted_surface") == "rejected" and
                        [row["path"] for row in successor_rows] == successor_paths and
                        cr15_derivation_transition.get(
                            "current_changed_text_surfaces") == successor_rows and
                        successor_other_digest == cr15_derivation_transition.get(
                            "unchanged_other_text_surface_manifest_digest"),
                        "Patch 24.0c CR-15 closure successor drifted")
                    for field in successor_unchanged:
                        require(derivation_current.get(field) ==
                                cr15_derivation_transition[
                                    "previous_inventory"].get(field),
                                f"Patch 24.0c changed closure inventory field: {field}")
                    if cr15_qualification_transition is not None:
                        qualification_unchanged = [
                            "text_surface_count", "invocation_count",
                            "invocation_manifest_digest", "structural_surface_count",
                            "structural_manifest_digest", "classification_counts",
                            "invocation_selection_counts", "unclassified_count",
                        ]
                        qualification_paths = cr15_qualification_transition.get(
                            "registered_changed_paths", [])
                        qualification_rows = (
                            [row for row in live_rows
                             if row["path"] in qualification_paths]
                            if cr15_seed_transition is None else
                            cr15_qualification_transition.get(
                                "current_changed_text_surfaces", [])
                        )
                        previous_rows = cr15_qualification_transition.get(
                            "previous_changed_text_surfaces", [])
                        qualification_current = (
                            current if cr15_seed_transition is None
                            else cr15_qualification_transition["current_inventory"]
                        )
                        require(
                            cr15_qualification_transition.get("contract_version") ==
                            "phase24_cr15_qualification_consumer_transition_v1" and
                            cr15_qualification_transition.get("status") ==
                            "patch24_0d_complete" and
                            cr15_qualification_transition.get(
                                "authority_base_main") ==
                            "2383096a741c62e8de103a5b79281b9f616eb805" and
                            cr15_qualification_transition.get(
                                "previous_inventory") ==
                            cr15_derivation_transition["current_inventory"] and
                            cr15_qualification_transition.get(
                                "current_inventory") ==
                            (current if cr15_seed_transition is None else
                             cr15_seed_transition.get("previous_inventory")) and
                            cr15_qualification_transition.get("unchanged_fields") ==
                            qualification_unchanged and
                            cr15_qualification_transition.get(
                                "partial_extra_or_substituted_surface") ==
                            "rejected" and
                            [row["path"] for row in qualification_rows] ==
                            qualification_paths and
                            cr15_qualification_transition.get(
                                "current_changed_text_surfaces") == qualification_rows and
                            [row.get("path") for row in previous_rows] ==
                            qualification_paths and
                            all(previous != live for previous, live in
                                zip(previous_rows, qualification_rows)) and
                            (module.canonical_digest([
                                row for row in live_rows
                                if row["path"] not in qualification_paths
                            ]) if cr15_seed_transition is None else
                             cr15_qualification_transition.get(
                                 "unchanged_other_text_surface_manifest_digest")) ==
                            cr15_qualification_transition.get(
                                "unchanged_other_text_surface_manifest_digest"),
                            "Patch 24.0d CR-15 closure successor drifted")
                        for field in qualification_unchanged:
                            require(
                                qualification_current.get(field) ==
                                cr15_qualification_transition[
                                    "previous_inventory"].get(field),
                                f"Patch 24.0d changed closure inventory field: {field}")
                        if cr15_seed_transition is not None:
                            seed_paths = [
                                "compiler/CRANELIFT_PHASE22_DEFAULT_ROUTE_SEED_CONVERGENCE.md",
                                "scripts/cranelift_registry.py",
                                "scripts/phase22_default_route_seed_convergence.py",
                                "scripts/phase23_closure.py",
                            ]
                            seed_rows = (
                                [row for row in live_rows
                                 if row["path"] in seed_paths]
                                if cr15_seed_publication is None else
                                cr15_seed_transition.get(
                                    "current_changed_text_surfaces", [])
                            )
                            previous_seed_rows = cr15_seed_transition.get(
                                "previous_changed_text_surfaces", [])
                            seed_current = (
                                current if cr15_seed_publication is None
                                else cr15_seed_transition["current_inventory"]
                            )
                            require(
                                cr15_seed_transition.get("contract_version") ==
                                "phase24_cr15_seed_authority_consumer_transition_v1" and
                                cr15_seed_transition.get("status") ==
                                "ready_for_seed_publication" and
                                cr15_seed_transition.get("authority_base_main") ==
                                "10076805b56697304e7b236fff09cdf3689fcc05" and
                                cr15_seed_transition.get("previous_inventory") ==
                                cr15_qualification_transition["current_inventory"] and
                                cr15_seed_transition.get("current_inventory") ==
                                (current if cr15_seed_publication is None else
                                 cr15_seed_publication.get("previous_inventory")) and
                                cr15_seed_transition.get("registered_changed_paths") ==
                                seed_paths and
                                cr15_seed_transition.get("unchanged_fields") ==
                                qualification_unchanged and
                                cr15_seed_transition.get(
                                    "partial_extra_or_substituted_surface") ==
                                "rejected" and
                                [row["path"] for row in seed_rows] == seed_paths and
                                cr15_seed_transition.get(
                                    "current_changed_text_surfaces") == seed_rows and
                                [row.get("path") for row in previous_seed_rows] ==
                                seed_paths and
                                all(previous != live for previous, live in
                                    zip(previous_seed_rows, seed_rows)) and
                                (module.canonical_digest([
                                    row for row in live_rows
                                    if row["path"] not in seed_paths
                                ]) if cr15_seed_publication is None else
                                 cr15_seed_transition.get(
                                     "unchanged_other_text_surface_manifest_digest")) ==
                                cr15_seed_transition.get(
                                    "unchanged_other_text_surface_manifest_digest"),
                                "Patch 24.0e CR-15 closure successor drifted")
                            for field in qualification_unchanged:
                                require(
                                    seed_current.get(field) ==
                                    cr15_seed_transition[
                                        "previous_inventory"].get(field),
                                    f"Patch 24.0e changed closure inventory field: {field}")
                            if cr15_seed_publication is not None:
                                if cr15_closure_transition is not None:
                                    module.validate_phase24_cr15_closure_transition(
                                        registry, current, live_rows)
                                else:
                                    module.validate_phase24_cr15_seed_publication_transition(
                                        registry, current, live_rows)

    require(closure.get("unresolved_material_findings") == 0,
            "closure has unresolved material findings")
    require(closure.get("non_claims") and
            len(closure["non_claims"]) == len(set(closure["non_claims"])),
            "closure non-claims are empty or duplicated")
    require(closure.get("boundary") == {
        "changes_accepted_Gust_program_meaning": False,
        "adds_or_changes_MIR_operations": False,
        "changes_ABI_layout_runtime_symbols_target_or_linker": False,
        "changes_backend_route_default_or_fallback": False,
        "changes_bootstrap_route_or_seed": False,
        "edits_stdlib_or_CR15": False,
        "begins_phase24_or_phase25": False,
    }, "closure boundary widened")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    require(levels.get(GUARD) == 1, "closure guard is not Level 1")
    just = JUSTFILE.read_text(encoding="utf-8")
    require(f"{GUARD}:" in just, "closure guard recipe is missing")
    require(f"just {GUARD}" in PR_FAST.read_text(encoding="utf-8"),
            "PR Fast does not own the Phase 23 closure guard")
    workflow = WORKFLOW.read_text(encoding="utf-8")
    require(f"just {GUARD}" in workflow and
            "just guard-cranelift-phase23-cross-feature-qualification-evidence" in workflow,
            "closure workflow omits contract or complete Phase 23 evidence")
    pull_paths = event_paths(workflow, "pull_request", "push")
    push_paths = event_paths(workflow, "push", "workflow_dispatch")
    for required_input in (
        "TASK.md", "Makefile", "README.md", "gust_v4.c", "compiler/**",
        "docs/**", "src/runtime.c", "src/runtime/**",
        "tools/normalize_generated_arena_offsets.py", "scripts/**",
        "tests/**", ".github/workflows/**", "justfile*",
    ):
        marker = f"      - '{required_input}'"
        require(marker in pull_paths and marker in push_paths,
                f"closure workflow omits authority input {required_input}")
    contract = CONTRACT.read_text(encoding="utf-8")
    for requirement in (
        "every Phase 23 status row is DONE",
        "checkpoint issues are closed on merged current-main evidence",
        "Assurance A and B remain deterministic and report-only",
        "explicit C remains accepted byte-identical deprecated and no-fallback",
        "one focused live lane and the archived corpus remain complete",
        "supported production package install and release routes are native",
        "the Phase 25 bootstrap chain remains explicit and fixed-point",
        "the exact-final-main Historical Full gate is complete success",
        "the closure view is generated from registry authority",
    ):
        require(requirement in contract,
                f"closure contract omits {requirement!r}")
    require(VIEW.is_file() and VIEW.read_text(encoding="utf-8") == render(closure),
            "generated closure view is stale; run --write")
    print(f"{GUARD}: ok ({len(EXPECTED_PATCHES)} patches, "
          f"{historical['successful_jobs']}/{historical['total_jobs']} historical jobs, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        VIEW.write_text(render(registry["phase23_closure"]), encoding="utf-8")
    check()


if __name__ == "__main__":
    main()
