#!/usr/bin/env python3
"""Validate and render the Patch 21.18 Phase 21 closure statement."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase21-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
VIEW = ROOT / "docs/PHASE21_CLOSURE.md"
JUSTFILE = ROOT / "justfile"
PR_FAST = ROOT / ".github/workflows/pr-fast.yml"
CONTRACT = ROOT / "tests/cranelift/phase21_closure_contract.tsv"

EXPECTED_PATCHES = [
    "21.0", "21.1", "21.2", "21.3", "21.4", "21.5", "21.6", "21.7",
    "21.7a", "21.7b", "21.8", "21.9", "21.10", "21.11", "21.12",
    "21.13", "21.13a", "21.14", "21.15", "21.16", "21.16a", "21.16b",
    "21.17a", "21.17", "21.17b", "21.17c", "21.17d", "21.17e", "21.17f", "21.18",
]

EXPECTED_AUTHORITIES = {
    "phase21_roadmap": "patch21_0_complete",
    "phase21_opening": "patch21_1_complete",
    "phase21_inert_scoped_query_records": "patch21_2_complete",
    "phase21_typed_query_noop_surface": "patch21_3_complete",
    "phase21_trusted_scope_provenance": "patch21_4_complete",
    "phase21_per_root_obligations": "patch21_5_complete",
    "phase21_cross_tenant_capability": "patch21_6_complete",
    "phase21_od8_adversarial_verdict": "patch21_7_complete",
    "phase21_tenant_scope_seed_convergence": "patch21_7a_complete",
    "phase21_residue_migration_authority": "patch21_8_complete",
    "phase21_collection_string_native_source": "patch21_9_complete",
    "phase21_filesystem_allocation_native_source": "patch21_10_complete",
    "phase21_resource_sync_native_source": "patch21_11_complete",
    "phase21_compiler_support_native_qualification": "patch21_12_complete",
    "phase21_selected_compiler_module_qualification": "patch21_13_complete",
    "phase21_native_feature_seed_convergence": "patch21_13a_complete",
    "phase21_full_compiler_native_qualification": "patch21_14_complete",
    "phase21_cranelift_built_compiler_programs": "patch21_15_complete",
    "phase21_native_rebuild_reproducibility": "patch21_16_complete",
    "phase21_complete_guard_suite": "patch21_17_complete",
}


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def render(closure: dict, suite: dict) -> str:
    historical = closure["authoritative_historical_full"]
    complete = closure["authoritative_complete_guard_suite"]
    verdict = closure["od8_verdict"]
    rebuild = closure["native_rebuild"]
    lines = [
        "# Phase 21 Closure — Tenant-Scoped Queries and Cranelift Self-Hosting",
        "",
        "<!-- Generated by scripts/phase21_closure.py from the Cranelift feature",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Authoritative closure gates",
        "",
        f"- Historical workflow: `{historical['workflow']}`",
        f"- Historical run: `{historical['run_id']}`",
        f"- Historical event: `{historical['event']}`",
        f"- Exact merged Phase 21 head: `{historical['head_sha']}`",
        f"- Historical conclusion: `{historical['conclusion']}`",
        f"- Historical jobs: `{historical['successful_jobs']}/{historical['total_jobs']}` successful",
        f"- Complete-suite workflow: `{complete['workflow']}`",
        f"- Complete-suite run: `{complete['run_id']}`",
        f"- Exact pull-request head: `{complete['head_sha']}`",
        f"- Complete-suite jobs: `{complete['successful_jobs']}/{complete['total_jobs']}` successful",
        "",
        "## Bounded OD-8 verdict",
        "",
        f"- Status: `{verdict['status']}`",
        f"- Decision: `{verdict['decision']}`",
        f"- Claim scope: `{verdict['claim_scope']}`",
        "- Excluded claims: " + ", ".join(f"`{item}`" for item in verdict["excluded_claims"]),
        "",
        "## Native rebuild authority",
        "",
        f"- OD-15: `{rebuild['od15_resolution']}`",
        f"- Criterion: `{rebuild['criterion']}`",
        f"- Artifact identity: `{str(rebuild['all_artifact_bytes_equal']).lower()}`",
        "",
        "## Complete native guard-suite classification",
        "",
        f"- Inventory cases: `{suite['inventory']['total']}`",
        f"- Required native cases: `{suite['classification']['required_native_case_count']}`",
        f"- Owned deferrals: `{suite['classification']['total_classified_deferral_count']}`",
        f"- Compiler origin: `{suite['compiler_origin']}`",
        f"- Target backend: `{suite['target_backend']}`",
        "",
        "## Bootstrap fixed points",
        "",
        f"- Tenant-scope seed: `{closure['tenant_scope_seed_authority']}`",
        f"- Native-feature seed: `{closure['native_feature_seed_authority']}`",
        f"- Policy: `{closure['seed_fixed_point_policy']}`",
        "",
        "## What Phase 21 does not claim",
        "",
    ]
    lines += [f"- {claim}" for claim in closure["non_claims"]]
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase21_closure")
    require(isinstance(closure, dict), "closure authority missing")
    require(closure.get("version") == "phase21_closure_v1", "closure version drifted")
    require(closure.get("status") ==
            "phase21_closed_tenant_scope_and_cranelift_self_hosting_qualification",
            "closure status drifted")
    require(closure.get("authority_owner") ==
            "scripts/cranelift_feature_registry.json", "closure owner drifted")

    historical = closure.get("authoritative_historical_full", {})
    require(historical == {
        "workflow": "Cranelift Historical Full",
        "run_id": 33216889936,
        "event": "workflow_dispatch",
        "head_branch": "main",
        "head_sha": "acd9e13841215d3c1aaf6e56589d6bacd45c6d4e",
        "status": "completed",
        "conclusion": "success",
        "successful_jobs": 18,
        "total_jobs": 18,
    }, "authoritative Historical Full evidence drifted or is incomplete")

    complete = closure.get("authoritative_complete_guard_suite", {})
    require(complete == {
        "workflow": "Cranelift Phase 21 Complete Guard Suite",
        "run_id": 33166864658,
        "event": "pull_request",
        "head_sha": "8037c0091cdb389f19c1fcda7e5e156a78b82029",
        "status": "completed",
        "conclusion": "success",
        "successful_jobs": 2,
        "total_jobs": 2,
    }, "authoritative complete-suite evidence drifted or is incomplete")

    task = TASK.read_text(encoding="utf-8")
    immutable_marker = (
        "# Immutable Phase 21 Completion Record — Tenant-Scoped Typed Queries "
        "and Cranelift Self-Hosting Qualification"
    )
    require(immutable_marker in task,
            "TASK.md does not preserve the immutable Phase 21 record")
    phase21_record = task.split(immutable_marker, 1)[1].split(
        "# Immutable Phase 20 Completion Record", 1)[0]
    phase21 = phase21_record.split("## Status", 1)[1]
    rows = re.findall(r"^- \[([ x])\] Patch (21\.\d+[a-z]?) — .+$",
                      phase21, re.MULTILINE)
    require([patch for _, patch in rows] == EXPECTED_PATCHES,
            "Phase 21 status rows are missing, duplicated, or reordered")
    lines = re.findall(r"^- \[[ x]\] Patch 21\.\d+[a-z]? — .+$",
                       phase21, re.MULTILINE)
    require(all(mark == "x" and line.endswith(" — DONE")
                for (mark, _), line in zip(rows, lines)),
            "every Phase 21 status row must be DONE")
    require("## Phase 21 Closure Record" in task,
            "TASK.md does not record Phase 21 closure")
    flat = " ".join(task.split())
    require("run **33216889936**" in flat and historical["head_sha"] in flat and
            "**18/18** jobs" in flat,
            "TASK.md does not record the Historical Full closure gate")

    for key, expected_status in EXPECTED_AUTHORITIES.items():
        authority = registry.get(key)
        require(isinstance(authority, dict), f"required authority {key} is absent")
        require(authority.get("status") == expected_status, f"{key} status drifted")

    amendments = registry["phase21_roadmap"].get("amendments", [])
    require([(row.get("patch"), row.get("status")) for row in amendments] == [
        ("21.16a", "complete"), ("21.16b", "complete"),
        ("21.17a", "complete"), ("21.17b", "complete"),
        ("21.17c", "complete"), ("21.17d", "complete"),
        ("21.17e", "complete"), ("21.17f", "complete")],
        "Phase 21 amendment authority drifted")

    od8 = registry["phase21_od8_adversarial_verdict"]
    verdict = od8.get("verdict", {})
    require(verdict.get("od8_status") == "resolved_2026_08_25_bounded_positive",
            "OD-8 verdict is not the evidence-supported bounded positive result")
    require(verdict.get("in_scope_counterexamples") == [],
            "OD-8 has an in-scope compiling counterexample")
    excluded = {row.get("id") for row in od8.get("out_of_scope_probes", [])}
    require(excluded == {"unsafe_raw_SQL", "result_cache", "multi_step_flows",
                         "non_query_reads", "trusted_context_establishment"},
            "OD-8 excluded-claim boundary drifted")
    require(closure.get("od8_verdict") == {
        "status": verdict.get("od8_status"),
        "decision": verdict.get("decision"),
        "claim_scope": od8.get("claim_scope"),
        "excluded_claims": sorted(excluded),
    }, "closure OD-8 projection drifted")

    rebuild = registry["phase21_native_rebuild_reproducibility"]
    evidence = rebuild.get("decision_evidence", {})
    require(rebuild.get("od15_resolution") ==
            "resolved_2026_08_27_strict_binary_identity",
            "OD-15 strict binary-identity authority drifted")
    require(evidence.get("all_artifact_bytes_equal") is True and
            evidence.get("all_help_behavior_equal") is True and
            evidence.get("all_build_diagnostics_empty") is True and
            evidence.get("all_linker_logs_empty") is True,
            "native rebuild identity evidence is incomplete")
    require(closure.get("native_rebuild") == {
        "od15_resolution": rebuild.get("od15_resolution"),
        "criterion": rebuild["identity_contract"]["criterion"],
        "all_artifact_bytes_equal": True,
    }, "closure native-rebuild projection drifted")

    suite = registry["phase21_complete_guard_suite"]
    inventory = suite["inventory"]["total"]
    native = suite["classification"]["required_native_case_count"]
    deferred = suite["classification"]["total_classified_deferral_count"]
    require((inventory, native, deferred) == (326, 192, 134) and
            native + deferred == inventory,
            "complete-suite classification does not account for all cases")
    require(all(row.get("owner") and row.get("destination") and row.get("falsifier")
                for key in ("oracle_precondition_failures", "runtime_divergences")
                for row in suite["classification"][key]),
            "complete-suite deferral lacks owner, destination, or falsifier")
    budgets = suite["budgets"]
    for observed, maximum in (
        ("observed_native_compiler_build_ms", "max_native_compiler_build_ms"),
        ("observed_corpus_suite_ms", "max_corpus_suite_ms"),
        ("observed_complete_suite_ms", "max_complete_suite_ms"),
        ("observed_peak_rss_kib", "max_peak_rss_kib"),
    ):
        require(budgets[observed] <= budgets[maximum], f"budget {observed} exceeded")

    tenant_seed = registry["phase21_tenant_scope_seed_convergence"]
    native_seed = registry["phase21_native_feature_seed_convergence"]
    require(closure.get("tenant_scope_seed_authority") == tenant_seed["contract_version"] and
            closure.get("native_feature_seed_authority") == native_seed["contract_version"] and
            closure.get("seed_fixed_point_policy") == "make_bootstrap_stage2_stage3_byte_identity",
            "closure seed authority drifted")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    require(levels.get(GUARD) == 1, "closure guard is not Level 1")
    require(f"{GUARD}:" in JUSTFILE.read_text(encoding="utf-8"),
            "closure guard recipe is missing")
    require(f"just {GUARD}" in PR_FAST.read_text(encoding="utf-8"),
            "PR Fast does not own the Phase 21 closure guard")
    contract = CONTRACT.read_text(encoding="utf-8")
    for requirement in (
        "every Phase 21 status row is DONE",
        "the bounded OD-8 verdict preserves every named exclusion",
        "the strict native rebuild identity criterion is satisfied",
        "all 326 complete-suite cases are required-native or owned deferrals",
        "Phase 21 authoritative Historical Full gate is satisfied",
        "the closure view is generated from registry authority",
    ):
        require(requirement in contract, f"closure contract omits {requirement!r}")
    require(closure.get("non_claims") and
            len(set(closure["non_claims"])) == len(closure["non_claims"]),
            "closure non-claims are empty or duplicated")
    require(VIEW.is_file() and VIEW.read_text(encoding="utf-8") ==
            render(closure, suite),
            "generated closure view is stale; run --write")
    print(f"{GUARD}: ok ({inventory} cases, {native} native, "
          f"{deferred} owned deferrals, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        VIEW.write_text(render(registry["phase21_closure"],
                               registry["phase21_complete_guard_suite"]),
                        encoding="utf-8")
    check()


if __name__ == "__main__":
    main()
