#!/usr/bin/env python3
"""Validate and render the Patch 18.19 Phase 18 closure statement."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase18-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
VIEW = ROOT / "docs/PHASE18_CLOSURE.md"


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def render(closure: dict) -> str:
    """Generate the closure document from registry-owned data.

    Phase 17.16 tried to police this text by scanning it for banned phrases, and
    the scan read the sentence "does not claim C runtime code has been removed"
    as making that very claim. Detection of prose is the wrong tool. The view is
    GENERATED from the registry instead, so an unowned claim cannot appear in it
    at all rather than having to be caught after the fact.
    """
    lines = [
        "# Phase 18 Closure — Target, Object, and Linker Hardening\n",
        "\n",
        "<!-- Generated by scripts/phase18_closure.py from the Cranelift feature\n",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->\n",
        "\n",
        f"Status: `{closure['status']}`\n",
        "\n",
        f"{closure['wording']}\n",
        "\n",
        "## What Phase 18 does not claim\n",
        "\n",
    ]
    lines += [f"- {claim}\n" for claim in closure["non_claims"]]
    return "".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text())
    closure = registry.get("phase18_closure")
    if not isinstance(closure, dict) or closure.get("version") != "phase18_closure_v1":
        fail("closure authority missing")

    # Closure is only honest if every earlier patch actually closed. Each Phase 18
    # authority advertises the patch that follows it; the chain must terminate at
    # the closure itself rather than at a patch that never landed.
    # Each authority advertises both the patch that follows it (next_patch) and
    # a status naming that same patch. The honest invariant is that those two
    # agree: a block whose status says "ready_for_patch18_16" while its
    # next_patch says 18.17 has drifted, and one of the two is a lie.
    #
    # Note "ready_for_patch18_19" on the deferral audit is CORRECT here, not
    # dangling -- 18.19 is this closure, so the chain terminates at it.
    for key, value in sorted(registry.items()):
        if not key.startswith("phase18_") or not isinstance(value, dict):
            continue
        status, following = value.get("status"), value.get("next_patch")
        if not isinstance(status, str) or not status.startswith("ready_for_patch18_"):
            continue
        if not following:
            fail(f"{key} declares a status pointing forward but names no next patch")
        expected = "ready_for_patch18_" + str(following).split(".", 1)[1]
        if status != expected:
            fail(f"{key}: status {status} disagrees with next_patch {following}")

    # The chain must actually terminate at this closure rather than at a patch
    # that never landed.
    if registry["phase18_deferrals"]["next_patch"] != "18.19":
        fail("the deferral audit does not hand off to this closure")

    # Closure depends on the two patches that make the phase's claims checkable.
    for required in ("phase18_composition", "phase18_deferrals"):
        if required not in registry:
            fail(f"cannot close: {required} is absent, so the phase's claims are unverified")

    # The exit gate: every declared supported target carries all six evidence
    # kinds. Recomputed here rather than trusting 18.17's own conclusion.
    evidence = registry["phase18_composition"]["per_target_evidence"]
    required_kinds = set(registry["phase18_composition"]["evidence_kinds"])
    if not evidence:
        fail("cannot close: no target carries complete evidence")
    for row in evidence:
        if set(row["evidence_kinds"]) != required_kinds:
            fail(f"cannot close: {row['target_id']} does not carry complete evidence")

    # Every non-claim must be registry-owned; the wording is not free prose.
    if not closure["non_claims"]:
        fail("a closure that disclaims nothing is a closure that overclaims")
    if len(set(closure["non_claims"])) != len(closure["non_claims"]):
        fail("a non-claim is stated twice")

    rendered = render(closure)
    if not VIEW.is_file() or VIEW.read_text() != rendered:
        fail("generated closure view is stale; run --write")

    print(f"{GUARD}: ok (phase closed, {len(evidence)} target(s) with complete evidence, "
          f"{len(closure['non_claims'])} explicit non-claims, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text())
        VIEW.write_text(render(registry["phase18_closure"]))
    check()


if __name__ == "__main__":
    main()
