#!/usr/bin/env python3
"""Validate and render the Patch 19.12 Phase 19 closure statement."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase19-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
STDLIB_TASK = ROOT / "TASK_STDLIB.md"
SHARED_ZONE = ROOT / "docs/SHARED_SEMANTIC_ZONE.md"
VIEW = ROOT / "docs/PHASE19_CLOSURE.md"
JUSTFILE = ROOT / "justfile"
HISTORICAL = ROOT / ".github/workflows/cranelift-historical-full.yml"
CONTRACT = ROOT / "tests/cranelift/phase19_closure_contract.tsv"

LEGACY_IDENTIFIERS = (
    "phase19_legacy_brand_spellings",
    "phase19_legacy_brand_spelling_is_exact",
    "phase19_legacy_brand_from_suffix",
    "phase19_legacy_brand_spelling_in_expression",
    "typechecker_extract_brand_from_suffix",
    "typechecker_clean_monomorphized_name",
)

EXPECTED_SUCCESSORS = {
    "phase19_spelling_inventory": "19.2",
    "phase19_brand_authority": "19.3",
    "phase19_type_naming": "19.4",
    "phase19_classification": "19.5",
    "phase19_representation": "19.6",
    "phase19_rule_convergence": "19.7",
    "phase19_retired_prototype_absence": "19.8",
    "phase19_gust_name_list_removed": "19.9",
    "phase19_seed_convergence": "19.12",
    "phase19_self_compilation_differential": "19.12",
    "phase19_composition": "19.12",
}


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def section(text: str, heading: str) -> str:
    marker = f"### {heading}"
    require(marker in text, f"missing section {heading!r}")
    body = text.split(marker, 1)[1]
    return body.split("\n### ", 1)[0]


def render(closure: dict) -> str:
    lines = [
        "# Phase 19 Closure — Brand Identity and Value Representation",
        "",
        "<!-- Generated by scripts/phase19_closure.py from the Cranelift feature",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Resolved defects",
        "",
    ]
    lines += [
        f"- `{row['id']}` — `{row['disposition']}`"
        for row in closure["resolved_defects"]
    ]
    lines += ["", "## Rename-invariance evidence", ""]
    lines += [
        f"- `{row['id']}` — `{row['guard']}` (Level {row['level']})"
        for row in closure["rename_invariance_families"]
    ]
    lines += ["", "## Explicit residue", ""]
    lines += [
        f"- `{row['id']}` — owner `{row['owner']}`; `{row['disposition']}`; "
        f"reason `{row['reason_code']}`"
        for row in closure["residue"]
    ]
    lines += ["", "## What Phase 19 does not claim", ""]
    lines += [f"- {claim}" for claim in closure["non_claims"]]
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase19_closure")
    require(isinstance(closure, dict), "closure authority missing")
    require(closure.get("version") == "phase19_closure_v1", "closure version drifted")
    require(
        closure.get("status") == "phase19_ready_for_authoritative_historical_full",
        "closure status drifted",
    )

    task = TASK.read_text(encoding="utf-8")
    status = task.split("## Status", 1)[1].split("## Immutable Phase 18", 1)[0]
    rows = re.findall(r"^- \[([ x])\] Patch (19\.\d+) — .+$", status, re.MULTILINE)
    require([patch for _, patch in rows] == [f"19.{i}" for i in range(13)],
            "Phase 19 status rows are missing, duplicated, or reordered")
    require(all(mark == "x" and row.endswith(" — DONE")
                for (mark, _), row in zip(rows, re.findall(r"^- \[[ x]\] Patch 19\.\d+ — .+$", status, re.MULTILINE))),
            "every Phase 19 status row must be DONE")
    require("## Phase 19 Closure Record" in task, "TASK.md does not record the closure fix")
    require("D-1 fix: identifier spelling is no longer semantic authority" in task,
            "TASK.md does not record the D-1 fix")
    require("Phase 19 is not closed until" in task and
            "Historical Full on the merged `main` commit succeeds" in task,
            "TASK.md does not retain the authoritative post-merge closure gate")

    for key, successor in EXPECTED_SUCCESSORS.items():
        authority = registry.get(key)
        require(isinstance(authority, dict), f"required authority {key} is absent")
        require(authority.get("next_patch") == successor,
                f"{key} does not hand off to Patch {successor}")

    compiler_sources = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / "compiler").glob("*.gst"))
    )
    for identifier in LEGACY_IDENTIFIERS:
        require(identifier not in compiler_sources,
                f"spelling-derived semantic consumer remains: {identifier}")
    semantic_sources = (
        (ROOT / "compiler/typechecker.gst").read_text(encoding="utf-8")
        + (ROOT / "compiler/codegen.gst").read_text(encoding="utf-8")
    )
    require(re.search(
        r'std\.str_(?:eq|find)\([^\n]*"(?:ctx|connCtx|arena|a|ctx1|ctx2|innerCtx|'
        r'outerCtx|current_ctx|next_ctx|main_ctx|bg_ctx|file_ctx)"',
        semantic_sources,
    ) is None, "identifier spelling still participates in a semantic decision")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    families = closure.get("rename_invariance_families")
    require(isinstance(families, list) and len(families) == 5,
            "rename-invariance family inventory must contain five families")
    ids = set()
    for family in families:
        require(family["id"] not in ids, f"duplicate rename family {family['id']}")
        ids.add(family["id"])
        require(levels.get(family["guard"]) == family["level"],
                f"{family['id']} guard level drifted")
        require(len(family["fixtures"]) >= 2, f"{family['id']} lacks paired evidence")
        for fixture in family["fixtures"]:
            require((ROOT / fixture).is_file(), f"rename fixture is missing: {fixture}")
    justfile = JUSTFILE.read_text(encoding="utf-8")
    run_phase11 = justfile.split("    run_phase11() {", 1)[1].split("\n    }", 1)[0]
    require("just guard-cranelift-phase19-rename-invariance" in run_phase11,
            "Level 3 rename invariance is not owned by the phase11 historical shard")
    require("phase11) run_phase11" in justfile and "phase11)" in HISTORICAL.read_text(encoding="utf-8"),
            "Cranelift Historical Full does not route the rename-invariance shard")

    shared = SHARED_ZONE.read_text(encoding="utf-8")
    require("D-1" not in shared, "D-1 remains in the shared semantic zone")
    require("D-2 — Rust/self-hosted brand-rule divergence — closed" in shared,
            "the historical D-2 closure record was removed")

    stdlib = STDLIB_TASK.read_text(encoding="utf-8")
    cr2 = section(stdlib, "CR-2 — Brand identity from types, not identifier spelling")
    require(re.search(r"^\*\*(?:Status[^\n]*(?:resolved|closed)|Resolved[^\n]*)",
                      cr2,
                      re.IGNORECASE | re.MULTILINE) is not None,
            "Stdlib roadmap has not marked CR-2 resolved")
    require("S1.4, S1.5, S1.6 — CR-2" not in stdlib,
            "Stdlib parallelism table still assigns S1.4 through S1.6 to CR-2")
    require("Either sequence CR-2 into the Cranelift roadmap first" not in stdlib,
            "Stdlib parallelism warning still treats CR-2 as future work")
    require("Still open exactly as recorded: the brand-spelling defect (CR-2" not in stdlib,
            "Stdlib snapshot still calls CR-2 open")
    for patch, title in (
        ("S1.4", "Branded Collection Type Consistency"),
        ("S1.5", "Clone Arena Destination Normalization"),
        ("S1.6", "Stdlib Composition Regression Program"),
    ):
        body = section(stdlib, f"Patch {patch} — {title}")
        require("Blocked by CR-2." not in body, f"Stdlib {patch} remains blocked by CR-2")
        body_flat = " ".join(body.split())
        require(re.search(r"(?:unblocked.*CR-2|CR-2.*unblocked|after.*CR-2.*landed)",
                          body_flat,
                          re.IGNORECASE) is not None,
                f"Stdlib {patch} does not record its CR-2 release")

    self_compilation = registry["phase19_self_compilation_differential"]
    require(self_compilation["full_diff"]["unexplained_differences"] == 0,
            "compiler self-compilation has unexplained differences")
    residue = closure.get("residue")
    require(isinstance(residue, list) and len(residue) == 1,
            "closure residue is not the single owned generic-source deferral")
    require(residue[0]["owner"] == registry["phase19_composition"]["cranelift_capability"],
            "closure residue does not trace to the composition deferral owner")
    require(residue[0]["reason_code"] == registry["phase19_composition"]["cranelift_reason_code"],
            "closure residue reason does not trace to composition evidence")
    require(closure.get("non_claims") and
            len(set(closure["non_claims"])) == len(closure["non_claims"]),
            "closure non-claims are empty or duplicated")

    contract = CONTRACT.read_text(encoding="utf-8")
    for requirement in (
        "every Phase 19 status row is DONE",
        "identifier spelling is absent from compiler semantic decisions",
        "every rename-invariance family has registered evidence",
        "D-1 is absent while the D-2 closure record remains",
        "CR-2 is resolved and S1.4 through S1.6 are released from CR-2",
        "Phase 19 remains non-closed pending authoritative Historical Full",
        "the generic-source Cranelift deferral remains explicit without fallback",
    ):
        require(requirement in contract, f"closure contract omits {requirement!r}")

    require(VIEW.is_file() and VIEW.read_text(encoding="utf-8") == render(closure),
            "generated closure view is stale; run --write")
    print(f"{GUARD}: ok ({len(families)} rename families, "
          f"{len(residue)} explicit residue, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        VIEW.write_text(render(registry["phase19_closure"]), encoding="utf-8")
    check()


if __name__ == "__main__":
    main()
