#!/usr/bin/env python3
"""Validate and render the Patch 22.9 Phase 22 closure statement."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase22-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
VIEW = ROOT / "docs/PHASE22_CLOSURE.md"
JUSTFILE = ROOT / "justfile"
PR_FAST = ROOT / ".github/workflows/pr-fast.yml"
CONTRACT = ROOT / "tests/cranelift/phase22_closure_contract.tsv"
WORKFLOW = ROOT / ".github/workflows/phase22-close.yml"

EXPECTED_PATCHES = [
    "22.0", "22.1", "22.2", "22.2a", "22.2b", "22.3", "22.4",
    "22.5", "22.6", "22.6a", "22.7", "22.7a", "22.7b", "22.8",
    "22.9",
]

EXPECTED_AUTHORITIES = {
    "phase22_opening": "patch22_1_complete",
    "phase22_explicit_c_migration": "complete_post_relay",
    "phase22_native_implicit_output": "implementation_complete",
    "phase22_default_native_package": "qualification_complete",
    "phase22_preflip_default_cohort":
        "qualification_complete_default_flip_prerequisites_satisfied",
    "phase22_default_route_flip": "implementation_complete",
    "phase22_default_route_seed_convergence": "patch22_6a_complete",
    "phase22_postflip_qualification": "qualification_complete",
    "phase22_historical_route_successor": "corrective_prerequisite_complete",
    "phase22_stability_qualification":
        "one_time_exact_main_qualification_complete",
}


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def event_paths(workflow: str, event: str, next_event: str) -> str:
    start_marker = f"  {event}:"
    end_marker = f"  {next_event}:"
    require(start_marker in workflow and end_marker in workflow,
            f"workflow has no bounded {event} filter")
    return workflow.split(start_marker, 1)[1].split(end_marker, 1)[0]


def render(closure: dict) -> str:
    historical = closure["authoritative_latest_historical_full"]
    route = closure["route_authority"]
    delivery = closure["delivery_authority"]
    bootstrap = closure["bootstrap_authority"]
    lines = [
        "# Phase 22 Closure — Cranelift Default Backend Transition",
        "",
        "<!-- Generated by scripts/phase22_closure.py from the Cranelift feature",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Authoritative closure gate",
        "",
        f"- Workflow: `{historical['workflow']}`",
        f"- Run: `{historical['run_id']}`",
        f"- Event: `{historical['event']}`",
        f"- Exact final implementation head: `{historical['head_sha']}`",
        f"- Conclusion: `{historical['conclusion']}`",
        f"- Jobs: `{historical['successful_jobs']}/{historical['total_jobs']}` successful",
        "",
        "## Backend route",
        "",
        f"- Bare default: `{route['default_backend']}`",
        f"- Explicit native route: `{route['explicit_native_backend']}`",
        "- Explicit C spellings: " +
        ", ".join(f"`{item}`" for item in route["explicit_c_spellings"]),
        f"- Explicit C role: `{route['explicit_c_role']}`",
        f"- Fallback: `{route['fallback']}`",
        "",
        "## Delivery and bootstrap",
        "",
        "- Package artifacts: " +
        ", ".join(f"`{item}`" for item in delivery["package_artifacts"]),
        f"- Install/relocation unit: `{delivery['install_and_relocation_unit']}`",
        f"- Bootstrap route: `{bootstrap['route']}`",
        f"- Seed authority: `{bootstrap['authority']}`",
        f"- Seed fixed point: `{bootstrap['fixed_point_policy']}`",
        "",
        "## What Phase 22 does not claim",
        "",
    ]
    lines += [f"- {claim}" for claim in closure["non_claims"]]
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase22_closure")
    require(isinstance(closure, dict), "closure authority missing")
    require(closure.get("version") == "phase22_closure_v1",
            "closure version drifted")
    require(closure.get("status") ==
            "phase22_closed_cranelift_default_with_retained_explicit_c_oracle",
            "closure status drifted")
    require(closure.get("authority_owner") ==
            "scripts/cranelift_feature_registry.json", "closure owner drifted")

    for key, expected_status in EXPECTED_AUTHORITIES.items():
        authority = registry.get(key)
        require(isinstance(authority, dict), f"required authority {key} is absent")
        require(authority.get("status") == expected_status,
                f"{key} status drifted")

    task = TASK.read_text(encoding="utf-8")
    require(task.startswith("# Phase 23 — MIR-to-C Deprecation"),
            "TASK.md does not open the active Phase 23 roadmap")
    immutable_marker = (
        "# Immutable Phase 22 Completion Record — Cranelift Default Backend "
        "Transition"
    )
    require(immutable_marker in task,
            "TASK.md does not preserve the immutable Phase 22 record")
    phase22_record = task.split(immutable_marker, 1)[1].split(
        "# Immutable Phase 21 Completion Record", 1)[0]
    active = phase22_record.split("## Status", 1)[1]
    rows = re.findall(r"^- \[([ x])\] Patch (22\.\d+[a-z]?) — .+$",
                      active, re.MULTILINE)
    require([patch for _, patch in rows] == EXPECTED_PATCHES,
            "Phase 22 status rows are missing, duplicated, or reordered")
    lines = re.findall(r"^- \[[ x]\] Patch 22\.\d+[a-z]? — .+$",
                       active, re.MULTILINE)
    require(all(mark == "x" and line.endswith(" — DONE")
                for (mark, _), line in zip(rows, lines)),
            "every Phase 22 status row must be DONE")
    require("## Phase 22 Closure Record" in task,
            "TASK.md does not record Phase 22 closure")

    historical = closure.get("authoritative_latest_historical_full", {})
    require(historical == {
        "workflow": "Cranelift Historical Full",
        "run_id": 33303824486,
        "event": "schedule",
        "head_branch": "main",
        "head_sha": "a7adbcd186512a3b4fd99b953bb2bc30f6838c52",
        "status": "completed",
        "conclusion": "success",
        "successful_jobs": 18,
        "total_jobs": 18,
        "unfinished_jobs": 0,
        "non_success_jobs": 0,
    }, "latest exact-main Historical Full evidence drifted or is incomplete")
    flat = " ".join(task.split())
    require(f"run **{historical['run_id']}**" in flat and
            historical["head_sha"] in flat and "**18/18** jobs" in flat,
            "TASK.md does not record the Historical Full closure gate")

    stability = registry["phase22_stability_qualification"]
    stability_run = stability["authoritative_historical_full"]
    require(stability_run["conclusion"] == "success" and
            stability_run["successful_jobs"] == stability_run["total_jobs"] == 18 and
            stability_run["head_sha"] == historical["head_sha"],
            "one-time stability evidence is not green on the final implementation head")
    require(closure.get("stability_authority") ==
            stability["contract_version"], "stability authority projection drifted")

    route = registry["phase22_default_route_flip"]["route_contract"]
    require(closure.get("route_authority") == route,
            "default and retained-C route projection drifted")
    require(route == {
        "default_backend": "cranelift",
        "explicit_native_backend": "cranelift",
        "default_and_explicit_native_route":
            "identical_shared_post_semantic_pipeline_route",
        "explicit_c_spellings": ["mir-to-c", "c"],
        "explicit_c_role": "retained_semantic_oracle",
        "native_implicit_output":
            "source_directory_and_exact_terminal_dot_gst_stem",
        "native_package": "executable_relative_three_artifact_sibling_package",
        "fallback": "forbidden",
        "bootstrap_route": "explicit_mir_to_c",
    }, "final backend route contract drifted")

    postflip = registry["phase22_postflip_qualification"]
    require(closure.get("delivery_authority") == postflip["delivery_contract"],
            "delivery authority projection drifted")
    qualification = postflip["qualification"]
    require(all(value == "qualified" for key, value in qualification.items()
                if key.endswith("_default")),
            "repository/install/relocation package qualification drifted")
    require(qualification.get("bare_and_explicit_native") ==
            "artifact_and_behavior_identical" and
            qualification.get("explicit_c_spellings") ==
            "byte_identical_and_executable" and
            qualification.get("missing_native_worker") ==
            "bare_default_fails_without_fallback_and_explicit_c_succeeds",
            "post-flip identity, explicit-C, or no-fallback evidence drifted")

    seed = registry["phase22_default_route_seed_convergence"]
    require(closure.get("bootstrap_authority") == {
        "route": seed["bootstrap_route"],
        "authority": seed["contract_version"],
        "fixed_point_policy": seed["fixed_point_policy"],
    }, "bootstrap authority projection drifted")

    require(closure.get("completed_authorities") ==
            {key: registry[key].get("contract_version")
             for key in EXPECTED_AUTHORITIES},
            "completed authority version projection drifted")
    require(closure.get("non_claims") and
            len(set(closure["non_claims"])) == len(closure["non_claims"]),
            "closure non-claims are empty or duplicated")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    require(levels.get(GUARD) == 1, "closure guard is not Level 1")
    require(f"{GUARD}:" in JUSTFILE.read_text(encoding="utf-8"),
            "closure guard recipe is missing")
    require(f"just {GUARD}" in PR_FAST.read_text(encoding="utf-8"),
            "PR Fast does not own the Phase 22 closure guard")
    workflow = WORKFLOW.read_text(encoding="utf-8")
    pull_paths = event_paths(workflow, "pull_request", "push")
    push_paths = event_paths(workflow, "push", "workflow_dispatch")
    for required_input in (
        "TASK.md", "Makefile", "README.md", "gust_v4.c", "compiler/*.gst",
        "compiler/experiments/cranelift/**", "docs/ONE_WAY_LEDGER.md",
        "docs/PHASE22_CLOSURE.md", "src/runtime.c", "src/runtime/**",
        "tools/normalize_generated_arena_offsets.py", "scripts/*.py",
        "scripts/*.sh", "scripts/cranelift_feature_registry.json",
        "scripts/cranelift_feature_registry.schema.json",
        "scripts/cranelift_registry.py", "scripts/cranelift_test_levels.json",
        "tests/cranelift/phase22_closure_contract.tsv", "tests/*.gst",
        ".github/workflows/cranelift-historical-full.yml",
        ".github/workflows/phase22-*.yml", ".github/workflows/pr-fast.yml",
        "justfile*",
    ):
        marker = f"      - '{required_input}'"
        require(marker in pull_paths and marker in push_paths,
                f"closure workflow omits authority input {required_input}")
    contract = CONTRACT.read_text(encoding="utf-8")
    for requirement in (
        "every Phase 22 status row is DONE",
        "bare and explicit Cranelift share one route with no fallback",
        "explicit C remains the byte-identical oracle and rollback route",
        "package install relocation and bootstrap authorities remain green",
        "latest exact-main Historical Full gate is satisfied",
        "the closure view is generated from registry authority",
    ):
        require(requirement in contract,
                f"closure contract omits {requirement!r}")
    require(VIEW.is_file() and VIEW.read_text(encoding="utf-8") ==
            render(closure),
            "generated closure view is stale; run --write")
    print(f"{GUARD}: ok ({len(EXPECTED_PATCHES)} patches, "
          f"{historical['successful_jobs']}/{historical['total_jobs']} historical jobs, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        VIEW.write_text(render(registry["phase22_closure"]), encoding="utf-8")
    check()


if __name__ == "__main__":
    main()
