#!/usr/bin/env python3
"""Validate and render the Patch 20.17 Phase 20 closure statement."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GUARD = "guard-cranelift-phase20-close"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
LEVELS = ROOT / "scripts/cranelift_test_levels.json"
TASK = ROOT / "TASK.md"
SHARED_ZONE = ROOT / "docs/SHARED_SEMANTIC_ZONE.md"
VIEW = ROOT / "docs/PHASE20_CLOSURE.md"
JUSTFILE = ROOT / "justfile"
PR_FAST = ROOT / ".github/workflows/pr-fast.yml"
HISTORICAL = ROOT / ".github/workflows/cranelift-historical-full.yml"
CONTRACT = ROOT / "tests/cranelift/phase20_closure_contract.tsv"

EXPECTED_PATCHES = [
    "20.0", "20.1", "20.2", "20.3", "20.3a", "20.4", "20.5", "20.6",
    "20.7", "20.8", "20.9", "20.9a", "20.10", "20.11", "20.12",
    "20.13", "20.14", "20.14h", "20.14a", "20.14b", "20.15", "20.16",
    "20.16a", "20.16b", "20.16c", "20.16d", "20.16e", "20.17",
]

EXPECTED_AUTHORITIES = {
    "phase20_brand_matching": "patch20_3_exact_boundaries_enabled",
    "phase20_nested_brand_annotation": "patch20_2_complete",
    "phase20_exact_brand_boundary": "patch20_3_complete",
    "phase20_contextual_generic_constructor": "patch20_3a_complete",
    "phase20_arena_lifecycle": "patch20_4_complete_observation_only",
    "phase20_arena_free_invalidation": "patch20_5_complete",
    "phase20_inert_resource_surface": "patch20_6_complete",
    "phase20_resource_declaration_migration": "patch20_7_complete",
    "phase20_resource_declaration_enforcement": "patch20_8_complete",
    "phase20_resource_acquisition_obligations": "patch20_10_complete",
    "phase20_resource_scope_cleanup": "patch20_10_complete",
    "phase20_seed_convergence": "patch20_11_complete",
    "phase20_whole_program_corpus": "patch20_12_complete",
    "phase20_stdlib_runtime_differential": "patch20_13_complete",
    "phase20_generated_mir_scale": "patch20_14_complete",
    "phase20_generic_guard_prerequisites": "patch20_14a_complete",
    "phase20_post_prerequisite_seed_convergence": "patch20_14b_complete",
    "phase20_long_lived_concurrent": "patch20_15_complete",
    "phase20_cross_feature_qualification":
        "phase20_ready_for_authoritative_historical_full",
    "phase20_resource_rooted_access": "patch20_16b_complete",
    "phase20_unsafe_mutex_migration": "patch20_16c_complete",
    "phase20_protected_access_liveness": "patch20_16d_complete",
    "phase20_protected_access_seed_convergence": "patch20_16e_complete",
}


def fail(message: str) -> None:
    raise SystemExit(f"{GUARD}: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def render(closure: dict, qualification: dict) -> str:
    historical = closure["authoritative_historical_full"]
    audit = qualification["registry_audit"]
    lines = [
        "# Phase 20 Closure — Semantic Foundations and Qualification",
        "",
        "<!-- Generated by scripts/phase20_closure.py from the Cranelift feature",
        "     registry. Do not edit by hand; edit the registry and regenerate. -->",
        "",
        f"Status: `{closure['status']}`",
        "",
        closure["wording"],
        "",
        "## Authoritative closure gate",
        "",
        f"- Workflow: `{historical['workflow']}`",
        f"- Run: `{historical['run_id']}`",
        f"- Event: `{historical['event']}`",
        f"- Exact merged main: `{historical['head_sha']}`",
        f"- Conclusion: `{historical['conclusion']}`",
        f"- Jobs: `{historical['successful_jobs']}/{historical['total_jobs']}` successful",
        "",
        "## Resolved compiler-owned scenarios",
        "",
    ]
    lines += [
        f"- `{row['id']}` — authority `{row['authority']}`; "
        f"`{row['guard']}` (Level {row['level']})"
        for row in closure["resolved_scenarios"]
    ]
    lines += [
        "",
        "## Selected qualification and explicit residue",
        "",
        f"- Registry entries: `{audit['entry_count']}`",
        f"- Migrated: `{audit['migrated']}`",
        f"- Candidate deferred: `{audit['candidate_deferred']}`",
        f"- Replaced: `{audit['replaced']}`",
        f"- Deferred: `{audit['deferred']}`",
        f"- Duplicate IDs: `{audit['duplicate_ids']}`",
        f"- Unowned rows: `{audit['unowned_rows']}`",
        f"- Unexplained divergences: `{len(qualification['unexplained_divergences'])}`",
        "",
    ]
    lines += [
        f"- `{row['category']}` — `{row['decision']}` / `{row['reason_code']}`; "
        f"owner `{row['owner']}`; destination `{row['destination']}`"
        for row in qualification["final_residues"]
    ]
    lines += [
        "",
        "## Bootstrap fixed point",
        "",
        f"- Authority: `{closure['seed_authority']}`",
        f"- Policy: `{closure['seed_fixed_point_policy']}`",
        "",
        "## What Phase 20 does not claim",
        "",
    ]
    lines += [f"- {claim}" for claim in closure["non_claims"]]
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    closure = registry.get("phase20_closure")
    require(isinstance(closure, dict), "closure authority missing")
    require(closure.get("version") == "phase20_closure_v1",
            "closure version drifted")
    require(closure.get("status") ==
            "phase20_closed_semantic_foundations_and_qualification",
            "closure status drifted")
    require(closure.get("authority_owner") ==
            "scripts/cranelift_feature_registry.json",
            "closure authority owner drifted")

    historical = closure.get("authoritative_historical_full", {})
    require(historical.get("workflow") == "Cranelift Historical Full",
            "Historical Full workflow drifted")
    require(historical.get("run_id") == 32772996884,
            "Historical Full run ID drifted")
    require(historical.get("event") == "workflow_dispatch",
            "Historical Full event drifted")
    require(historical.get("head_branch") == "main",
            "Historical Full branch drifted")
    require(historical.get("head_sha") ==
            "6e54e3cc6fa8fc44e5df7a67624bb183b01b2258",
            "Historical Full exact merged-main SHA drifted")
    require(historical.get("status") == "completed" and
            historical.get("conclusion") == "success",
            "Historical Full did not complete successfully")
    require(historical.get("successful_jobs") == historical.get("total_jobs") and
            isinstance(historical.get("total_jobs"), int) and
            historical["total_jobs"] >= 17,
            "Historical Full job population is incomplete")

    task = TASK.read_text(encoding="utf-8")
    status = task.split("## Status", 1)[1].split(
        "## Immutable Phase 19 Completion Record", 1)[0]
    rows = re.findall(r"^- \[([ x])\] Patch (20\.\d+[a-z]?) — .+$",
                      status, re.MULTILINE)
    require([patch for _, patch in rows] == EXPECTED_PATCHES,
            "Phase 20 status rows are missing, duplicated, or reordered")
    status_lines = re.findall(r"^- \[[ x]\] Patch 20\.\d+[a-z]? — .+$",
                              status, re.MULTILINE)
    require(all(mark == "x" and line.endswith(" — DONE")
                for (mark, _), line in zip(rows, status_lines)),
            "every Phase 20 status row must be DONE")
    require("## Phase 20 Closure Record" in task,
            "TASK.md does not record Phase 20 closure")
    task_flat = " ".join(task.split())
    require("run **32772996884**" in task_flat and
            historical["head_sha"] in task_flat and
            f"**{historical['successful_jobs']}/{historical['total_jobs']}** jobs"
            in task_flat,
            "TASK.md does not record the satisfied authoritative closure gate")

    for key, expected_status in EXPECTED_AUTHORITIES.items():
        authority = registry.get(key)
        require(isinstance(authority, dict), f"required authority {key} is absent")
        require(authority.get("status") == expected_status,
                f"{key} status drifted")

    levels = json.loads(LEVELS.read_text(encoding="utf-8"))["guards"]
    scenarios = closure.get("resolved_scenarios")
    require(isinstance(scenarios, list) and len(scenarios) == 7,
            "resolved compiler scenario inventory must contain seven rows")
    require(len({row["id"] for row in scenarios}) == len(scenarios),
            "resolved compiler scenario IDs are duplicated")
    for row in scenarios:
        require(row["authority"] in EXPECTED_AUTHORITIES,
                f"{row['id']} authority is outside Phase 20")
        require(levels.get(row["guard"]) == row["level"],
                f"{row['id']} guard level drifted")
        require(f"{row['guard']}:" in JUSTFILE.read_text(encoding="utf-8"),
                f"{row['id']} guard is missing")

    qualification = registry["phase20_cross_feature_qualification"]
    require(closure.get("residue_authority") ==
            qualification.get("contract_version"),
            "closure residue authority drifted")
    audit = qualification.get("registry_audit", {})
    require(audit.get("duplicate_ids") == 0 and audit.get("unowned_rows") == 0,
            "qualification audit has duplicate or unowned rows")
    require(qualification.get("unexplained_divergences") == [],
            "qualification has unexplained divergences")
    residue = qualification.get("final_residues")
    require(isinstance(residue, list) and len(residue) == 6,
            "final residue inventory drifted")
    for row in residue:
        require(row.get("owner") and row.get("reason_code") and
                row.get("falsifier") and row.get("destination") == "phase21_opening",
                f"residue {row.get('category')} is not owned and falsifiable")
    require("poisoned" in qualification.get("fallback_policy", "") and
            "without_an_artifact" in qualification.get("fallback_policy", ""),
            "explicit Cranelift no-fallback policy drifted")

    protected = registry["phase20_protected_access_liveness"]
    require(protected.get("handoff", {}).get(
        "implementation_authority_landed") is True,
        "OD-13 implementation authority has not landed")
    require(protected.get("raw_mutex_policy") ==
            "Mutex_Lock_and_Unlock_require_explicit_unsafe_while_lowering_runtime_symbols_ABI_layout_and_MIR_remain_unchanged",
            "raw/manual Mutex boundary drifted")
    seed = registry["phase20_protected_access_seed_convergence"]
    require(closure.get("seed_authority") == seed.get("contract_version") and
            closure.get("seed_fixed_point_policy") ==
            seed.get("fixed_point_policy"),
            "closure seed authority drifted")

    shared = SHARED_ZONE.read_text(encoding="utf-8")
    require("Patch 20.16e completed the isolated seed reconvergence" in shared,
            "shared-zone protected-access record is stale")
    require("Patch 20.16e remains the isolated seed reconvergence" not in shared,
            "shared-zone record still calls completed seed work future")
    require(f"just {GUARD}" in PR_FAST.read_text(encoding="utf-8"),
            "PR Fast does not own the Phase 20 closure guard")
    require("phase20) just guard-cranelift-phase20-cross-feature-qualification-full"
            in HISTORICAL.read_text(encoding="utf-8"),
            "Historical Full does not own the Phase 20 Level 3 shard")

    contract = CONTRACT.read_text(encoding="utf-8")
    for requirement in (
        "every Phase 20 status row is DONE",
        "all compiler-owned issue scenarios have focused registered guards",
        "the selected cohort has zero unexplained differences",
        "every deferred cohort is owned and falsifiable without fallback",
        "OD-13 implementation authority and its unsafe boundary are preserved",
        "the protected-access bootstrap seed reached its fixed point",
        "Phase 20 authoritative Historical Full gate is satisfied",
        "the closure view is generated from registry authority",
    ):
        require(requirement in contract, f"closure contract omits {requirement!r}")

    require(closure.get("non_claims") and
            len(set(closure["non_claims"])) == len(closure["non_claims"]),
            "closure non-claims are empty or duplicated")
    require(VIEW.is_file() and
            VIEW.read_text(encoding="utf-8") == render(closure, qualification),
            "generated closure view is stale; run --write")
    print(f"{GUARD}: ok ({len(scenarios)} resolved scenarios, "
          f"{len(residue)} explicit residues, level1)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        VIEW.write_text(render(registry["phase20_closure"],
                               registry["phase20_cross_feature_qualification"]),
                        encoding="utf-8")
    check()


if __name__ == "__main__":
    main()
