#!/usr/bin/env python3
"""Validate and project Patch 23.3 resource-acquisition parity authority."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
REVIEW = ROOT / "compiler/CRANELIFT_PHASE23_RESOURCE_ACQUISITION_PARITY.md"
TASK = ROOT / "TASK.md"
PHASE20_GUARD = ROOT / "scripts/phase20_resource_acquisition.sh"
GUARD = "guard-cranelift-phase23-resource-acquisition-parity-contract"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"{GUARD}: {message}")


def authority() -> dict:
    value = json.loads(REGISTRY.read_text(encoding="utf-8")).get(
        "phase23_resource_acquisition_parity"
    )
    require(isinstance(value, dict), "registry authority is missing")
    return value


def validate(value: dict | None = None) -> dict:
    value = authority() if value is None else value
    require(value.get("contract_version") == "phase23_resource_acquisition_parity_v1",
            "contract version drifted")
    require(value.get("status") ==
            "implementation_ready_pending_merged_current_main_closure",
            "implementation/closure state drifted")
    require(value.get("issue") == 240 and value.get("owner") == "cranelift",
            "issue or owner drifted")
    require(value.get("review_view") == REVIEW.relative_to(ROOT).as_posix(),
            "review view drifted")
    require(value.get("retained_guard") ==
            "guard-cranelift-phase20-resource-acquisition-parity",
            "retained guard identity drifted")
    require(value.get("oracle") == "explicit_mir_to_c",
            "MIR-to-C oracle authority drifted")
    require(value.get("native_route") ==
            "explicit_cranelift_with_absolute_packaged_driver_and_no_fallback",
            "native route authority drifted")
    require(value.get("positive_cases") == [
        {"id": "user", "source": "compiler/phase20_resource_acquisition_source.gst",
         "exit_status": 168, "stdout": "", "stderr": ""},
        {"id": "directory", "source": "compiler/phase20_resource_acquisition_directory_source.gst",
         "exit_status": 0, "stdout": "", "stderr": ""},
        {"id": "path_transfer", "source": "compiler/phase20_resource_acquisition_path_transfer_source.gst",
         "exit_status": 42, "stdout": "", "stderr": ""},
    ], "positive selection or observables drifted")
    require(value.get("falsifiers") == {
        "missing_driver": "supported_positive_fails_with_native_driver_discovery_diagnostic_and_preserves_requested_output",
        "missing_artifact": "each_successful_native_compile_publishes_a_nonempty_executable",
        "stale_deferral": "each_registered_positive_reaches_driver_and_matches_explicit_C_observables",
        "empty_selection": "exact_three_case_registry_selection_is_required",
    }, "falsifier inventory drifted")
    require(value.get("boundary") == {
        "preserves_issue106_resource_semantics": True,
        "preserves_negative_diagnostic_parity": True,
        "changes_accepted_Gust_program_meaning": False,
        "adds_or_changes_MIR_operations": False,
        "changes_backend_route_or_fallback": False,
        "changes_ABI_layout_or_runtime_symbols": False,
        "changes_bootstrap_seed": False,
        "edits_stdlib_or_CR15": False,
        "begins_patch23_4": False,
    }, "Patch 23.3 boundary drifted")
    require("- [x] Patch 23.3a — Structured Guard/Defer Native Admission — DONE" in
            TASK.read_text(encoding="utf-8"),
            "TASK does not record the merged Patch 23.3a prerequisite")
    require("phase23_resource_acquisition_parity.py positive-cases" in
            PHASE20_GUARD.read_text(encoding="utf-8"),
            "retained parity guard no longer consumes registry-owned selection")
    return value


def positive_cases(value: dict) -> None:
    for case in value["positive_cases"]:
        print(f"{case['id']}\t{case['source']}\t{case['exit_status']}")


def render(value: dict) -> str:
    lines = [
        "# Phase 23 Resource-Acquisition Parity Evidence Repair",
        "",
        "Generated by `scripts/phase23_resource_acquisition_parity.py`; do not edit by hand.",
        "",
        f"- Contract: `{value['contract_version']}`",
        f"- Status: `{value['status']}`",
        f"- Issue: `#{value['issue']}`",
        f"- Retained Level 2 guard: `{value['retained_guard']}`",
        f"- Oracle: `{value['oracle']}`",
        f"- Native route: `{value['native_route']}`",
        "",
        "## Exact positive cohort",
        "",
        "| ID | Source | Exit | stdout | stderr |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for case in value["positive_cases"]:
        lines.append(
            f"| `{case['id']}` | `{case['source']}` | {case['exit_status']} | "
            f"{len(case['stdout'])} | {len(case['stderr'])} |"
        )
    lines.extend([
        "",
        "Every selected positive is compiled through explicit MIR-to-C and through "
        "explicit Cranelift with the absolute packaged driver. The two executables "
        "must have identical exit status, stdout, and stderr. Each native compile "
        "must publish a nonempty executable.",
        "",
        "The retained guard also rejects a missing packaged driver while preserving a "
        "pre-existing requested output and requiring the native-driver discovery "
        "diagnostic. That prevents silent C fallback. All inherited #106 negative "
        "diagnostic parity and cleanup checks remain unchanged.",
        "",
        "This is evidence/control-plane repair only: it changes no accepted Gust "
        "meaning, canonical MIR operation, resource/move/cleanup semantics, "
        "ABI/layout/runtime symbol, backend route/fallback policy, bootstrap seed, "
        "Stdlib, or CR-15 authority.",
        "",
    ])
    return "\n".join(lines)


def check_review(value: dict) -> None:
    require(REVIEW.read_text(encoding="utf-8") == render(value),
            "generated review is stale; run render")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("validate", "positive-cases", "render", "check-review"))
    args = parser.parse_args()
    value = validate()
    if args.command == "positive-cases":
        positive_cases(value)
    elif args.command == "render":
        REVIEW.write_text(render(value), encoding="utf-8")
    elif args.command == "check-review":
        check_review(value)
    else:
        print("phase23_resource_acquisition_parity: ok")


if __name__ == "__main__":
    main()
