#!/usr/bin/env python3
"""Generate the stdlib surface inventory for TASK_STDLIB.md Patch S1.0.

The inventory is derived, never hand-written. Patch S1.3's method list claimed a
`Contains` method that has never existed on any receiver; that mistake reached a
roadmap because the surface was described from memory. This script describes it
from the compiler.

Sources of truth:
  * `std.*` names the typechecker registers        -> the user-facing named surface
  * `std_*` C symbols in src/runtime/              -> the runtime surface
  * Phase 17 helper rows in the Cranelift registry -> the symbols with an owner
  * collection method names the typechecker dispatches on a receiver

Usage:
  stdlib_surface_inventory.py generate   # write docs/STDLIB_SURFACE_INVENTORY.md
  stdlib_surface_inventory.py --check    # fail if the committed file is stale
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TYPECHECKER = ROOT / "compiler/typechecker.gst"
RUNTIME_DIR = ROOT / "src/runtime"
REGISTRY = ROOT / "scripts/cranelift_feature_registry.json"
OUTPUT = ROOT / "docs/STDLIB_SURFACE_INVENTORY.md"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def registered_std_names() -> list[str]:
    """`std.X` names the typechecker knows about."""
    return sorted(set(re.findall(r'"(std\.[A-Za-z_]+)"', read(TYPECHECKER))))


def runtime_symbols() -> dict[str, str]:
    """`std_*` C symbols, mapped to the file that defines them."""
    found: dict[str, str] = {}
    for c in sorted(RUNTIME_DIR.glob("*.c")):
        for name in re.findall(r"\bstd_[A-Za-z0-9_]+(?=\s*\()", read(c)):
            found.setdefault(name, f"src/runtime/{c.name}")
    return dict(sorted(found.items()))


def phase17_rows() -> dict[str, str]:
    """Phase 17 helper rows, mapped to their owning entry id."""
    blob = json.loads(read(REGISTRY))
    rows: dict[str, str] = {}

    def walk(node):
        if isinstance(node, dict):
            sym = node.get("symbol_identity")
            if isinstance(sym, str) and sym.startswith("std_"):
                # A symbol appears in several tables and only the helper
                # inventory carries the owning entry. Never let a later,
                # ownerless occurrence overwrite a real owner.
                owner = node.get("owning_phase17_entry_id")
                if owner or sym not in rows:
                    rows[sym] = owner or "unknown"
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(blob)
    return dict(sorted(rows.items()))


def collection_methods() -> list[str]:
    """Method names dispatched on a collection receiver."""
    text = read(TYPECHECKER)
    names = re.findall(r'std\.str_eq\(right_name, "([A-Za-z_]+)"\)', text)
    return sorted(set(names))


def render() -> str:
    names = registered_std_names()
    symbols = runtime_symbols()
    rows = phase17_rows()
    methods = collection_methods()

    unowned = [s for s in symbols if s not in rows]
    orphan_rows = [s for s in rows if s not in symbols]

    out: list[str] = []
    add = out.append
    add("# Stdlib Surface Inventory")
    add("")
    add("Generated by `scripts/stdlib_surface_inventory.py`. Do not edit by hand;")
    add("run `just guard-stdlib-s1-surface-inventory` to regenerate and verify.")
    add("")
    add("This exists because Patch S1.3's method list claimed a `Contains` method that")
    add("has never existed on any receiver. That reached a roadmap because the surface")
    add("was described from memory. This file describes it from the compiler.")
    add("")
    add("## Summary")
    add("")
    add("| | |")
    add("| --- | --- |")
    add(f"| `std.*` names the typechecker registers | {len(names)} |")
    add(f"| `std_*` C symbols in `src/runtime/` | {len(symbols)} |")
    add(f"| Phase 17 helper rows | {len(rows)} |")
    add(f"| **runtime symbols with no Phase 17 row** | **{len(unowned)}** |")
    add(f"| helper rows with no runtime symbol | {len(orphan_rows)} |")
    add(f"| collection methods dispatched on a receiver | {len(methods)} |")
    add("")
    add("## Runtime symbols and their Phase 17 owner")
    add("")
    add("Per `TASK_STDLIB.md` CR-4, every `std_*` runtime symbol should carry a Phase 17")
    add("registry row. Symbols listed as `none` do not, and are pre-existing gaps rather")
    add("than anything this inventory introduces.")
    add("")
    add("| Symbol | Defined in | Phase 17 owner |")
    add("| --- | --- | --- |")
    for sym, path in symbols.items():
        add(f"| `{sym}` | `{path}` | {'`' + rows[sym] + '`' if sym in rows else '**none**'} |")
    add("")
    if orphan_rows:
        add("## Helper rows with no runtime symbol")
        add("")
        for sym in orphan_rows:
            add(f"- `{sym}` (owner `{rows[sym]}`)")
        add("")
    add("## Names the typechecker registers")
    add("")
    add("Includes types and compiler-provided builtins, not only functions, so a name")
    add("here need not have a runtime symbol.")
    add("")
    for name in names:
        add(f"- `{name}`")
    add("")
    add("## Collection methods")
    add("")
    add("Dispatched on a receiver by the typechecker. A method absent from this list")
    add("does not exist on any receiver, by value or by reference.")
    add("")
    for method in methods:
        add(f"- `{method}`")
    add("")
    return "\n".join(out) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    generated = render()
    if check:
        if not OUTPUT.exists():
            print(f"Missing {OUTPUT.relative_to(ROOT)}; run the generator.", file=sys.stderr)
            return 1
        if read(OUTPUT) != generated:
            print(
                f"{OUTPUT.relative_to(ROOT)} is stale. Regenerate it with:\n"
                f"  python3 scripts/stdlib_surface_inventory.py generate",
                file=sys.stderr,
            )
            subprocess.run(
                ["diff", "-u", str(OUTPUT), "-"], input=generated, text=True, check=False
            )
            return 1
        print("stdlib surface inventory is current.")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
